/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2018 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
__int64 sub_400900();
// int printf(const char *format, ...);
// int puts(const char *s);
// __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD); weak
// void __noreturn exit(int status);
// void *malloc(size_t size);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int pthread_mutex_init(pthread_mutex_t *mutex, const pthread_mutexattr_t *mutexattr);
// int iswxdigit(wint_t wc);
// void free(void *ptr);
// int pthread_create(pthread_t *newthread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg);
// const unsigned __int16 **__ctype_b_loc(void);
// int pthread_join(pthread_t th, void **thread_return);
// void __noreturn pthread_exit(void *retval);
// int wprintf(const wchar_t *format, ...);
// __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD); weak
// void srand(unsigned int seed);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int rand(void);
// int pthread_mutex_destroy(pthread_mutex_t *mutex);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// time_t time(time_t *timer);
// __int64 _gmon_start__(void); weak
// void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>);
__int64 deregister_tm_clones();
__int64 register_tm_clones();
__int64 _do_global_dtors_aux();
__int64 frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
void CWE467_Use_of_sizeof_on_Pointer_Type__short_13_bad();
void good1();
void good2();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_13_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_10_bad();
void good1_0();
void good2_0();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_10_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_01_bad();
void good1_1();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_01_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_01_bad();
void good1_2();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_01_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_09_bad();
void good1_3();
void good2_1();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_09_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_09_bad();
void good1_4();
void good2_2();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_09_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_03_bad();
void good1_5();
void good2_3();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_03_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_14_bad();
void good1_6();
void good2_4();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_14_good();
__int64 staticReturnsTrue();
__int64 staticReturnsFalse();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_08_bad();
void good1_7();
void good2_5();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_08_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_14_bad();
void good1_8();
void good2_6();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_14_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_18_bad();
void good1_9();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_18_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_13_bad();
void good1_10();
void good2_7();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_13_good();
__int64 staticReturnsTrue_0();
__int64 staticReturnsFalse_0();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_08_bad();
void good1_11();
void good2_8();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_08_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_09_bad();
void good1_12();
void good2_9();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_09_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_12_bad();
void good1_13();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_12_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_12_bad();
void good1_14();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_12_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_04_bad();
void good1_15();
void good2_10();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_04_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_18_bad();
void good1_16();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_18_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_04_bad();
void good1_17();
void good2_11();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_04_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_03_bad();
void good1_18();
void good2_12();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_03_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_17_bad();
void good1_19();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_17_good();
__int64 staticReturnsTrue_1();
__int64 staticReturnsFalse_1();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_08_bad();
void good1_20();
void good2_13();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_08_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_14_bad();
void good1_21();
void good2_14();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_14_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_17_bad();
void good1_22();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_17_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_18_bad();
void good1_23();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_18_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_07_bad();
void good1_24();
void good2_15();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_07_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_11_bad();
void good1_25();
void good2_16();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_11_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_02_bad();
void good1_26();
void good2_17();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_02_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_07_bad();
void good1_27();
void good2_18();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_07_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_16_bad();
void good1_28();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_16_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_16_bad();
void good1_29();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_16_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_12_bad();
void good1_30();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_12_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_02_bad();
void good1_31();
void good2_19();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_02_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_10_bad();
void good1_32();
void good2_20();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_10_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_15_bad();
void good1_33();
void good2_21();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_15_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_15_bad();
void good1_34();
void good2_22();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_15_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_11_bad();
void good1_35();
void good2_23();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_11_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_07_bad();
void good1_36();
void good2_24();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_07_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_04_bad();
void good1_37();
void good2_25();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_04_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_06_bad();
void good1_38();
void good2_26();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_06_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_06_bad();
void good1_39();
void good2_27();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_06_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_01_bad();
void good1_40();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_01_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_17_bad();
void good1_41();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_17_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_05_bad();
void good1_42();
void good2_28();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_05_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_11_bad();
void good1_43();
void good2_29();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_11_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_02_bad();
void good1_44();
void good2_30();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_02_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_05_bad();
void good1_45();
void good2_31();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_05_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_03_bad();
void good1_46();
void good2_32();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_03_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_16_bad();
void good1_47();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_16_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_10_bad();
void good1_48();
void good2_33();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_10_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_05_bad();
void good1_49();
void good2_34();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_05_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_06_bad();
void good1_50();
void good2_35();
void CWE467_Use_of_sizeof_on_Pointer_Type__short_06_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_15_bad();
void good1_51();
void good2_36();
void CWE467_Use_of_sizeof_on_Pointer_Type__char_15_good();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_13_bad();
void good1_52();
void good2_37();
void CWE467_Use_of_sizeof_on_Pointer_Type__int_13_good();
int __fastcall printLine(const char *a1);
int __fastcall printWLine(__int64 a1);
int __fastcall printIntLine(unsigned int a1);
int __fastcall printShortLine(__int16 a1);
int __fastcall printFloatLine(float a1);
int __fastcall printLongLine(__int64 a1);
int __fastcall printLongLongLine(__int64 a1);
int __fastcall printSizeTLine(__int64 a1);
int __fastcall printHexCharLine(char a1);
int __fastcall printWcharLine(int a1);
int __fastcall printUnsignedLine(unsigned int a1);
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1);
int __fastcall printDoubleLine(double a1);
int __fastcall printStructLine(unsigned int *a1);
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2);
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3);
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3);
__int64 globalReturnsTrue();
__int64 globalReturnsFalse();
__int64 globalReturnsTrueOrFalse();
void good1_53();
void good2_38();
void good3();
void good4();
void good5();
void good6();
void good7();
void good8();
void good9();
void bad1();
void bad2();
void bad3();
void bad4();
void bad5();
void bad6();
void bad7();
void bad8();
void bad9();
void __fastcall __noreturn internal_start(void *a1);
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3);
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1);
__int64 __fastcall stdThreadDestroy(void *a1);
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1);
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1);
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1);
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

char s[3] = { '\0', '\0', '\0' }; // idb
int GLOBAL_CONST_TRUE = 1; // weak
int GLOBAL_CONST_FALSE = 0; // weak
int GLOBAL_CONST_FIVE = 5; // weak
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_60B010)(void) = NULL; // weak
int staticFive = 5; // weak
int staticFive_0 = 5; // weak
int staticFive_1 = 5; // weak
int staticTrue = 1; // weak
int staticTrue_0 = 1; // weak
int staticTrue_1 = 1; // weak
int globalTrue = 1; // weak
int globalFive = 5; // weak
char completed_6355; // weak
int staticFalse; // weak
int staticFalse_0; // weak
int staticFalse_1; // weak
int globalFalse; // weak
int globalArgc; // weak
__int64 globalArgv; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00000000004008D8) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 400A60: using guessed type __int64 _gmon_start__(void);

//----- (0000000000400900) ----------------------------------------------------
__int64 sub_400900()
{
  return qword_60B010();
}
// 60B010: using guessed type __int64 (*qword_60B010)(void);

//----- (0000000000400A70) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>)
{
  int v2; // esi
  int v3; // [rsp-8h] [rbp-8h]
  __int64 _0; // [rsp+0h] [rbp+0h]

  v2 = v3;
  *(_QWORD *)&v3 = a1;
  __libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v2,
    (char **)&_0,
    _libc_csu_init,
    _libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 400A76: positive sp value 8 has been found

//----- (0000000000400AA0) ----------------------------------------------------
__int64 deregister_tm_clones()
{
  __int64 result; // rax

  result = 6336751LL - (_QWORD)&completed_6355;
  if ( (unsigned __int64)(6336751LL - (_QWORD)&completed_6355) > 0xE )
    result = 0LL;
  return result;
}
// 60B0E8: using guessed type char completed_6355;

//----- (0000000000400AD0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (0000000000400B10) ----------------------------------------------------
__int64 _do_global_dtors_aux()
{
  __int64 result; // rax

  if ( !completed_6355 )
  {
    result = deregister_tm_clones();
    completed_6355 = 1;
  }
  return result;
}
// 60B0E8: using guessed type char completed_6355;

//----- (0000000000400B30) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 400B30: could not find valid save-restore pair for rbp

//----- (0000000000400B5D) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  unsigned int v3; // eax

  v3 = time(0LL);
  srand(v3);
  globalArgc = argc;
  globalArgv = (__int64)argv;
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_17_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_17_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_03_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_03_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_10_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_10_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_16_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_16_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_16_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_16_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_01_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_01_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_17_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_17_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_17_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_17_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_13_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_13_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_02_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_02_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_13_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_13_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_10_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_10_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_02_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_02_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_08_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_08_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_04_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_04_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_14_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_14_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_15_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_15_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_18_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_18_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_16_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_16_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_04_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_04_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_13_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_13_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_12_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_12_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_06_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_06_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_15_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_15_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_06_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_06_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_08_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_08_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_14_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_14_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_01_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_01_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_11_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_11_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_12_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_12_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_11_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_11_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_08_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_08_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_07_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_07_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_05_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_05_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_12_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_12_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_10_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_10_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_09_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_09_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_09_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_09_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_01_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_01_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_09_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_09_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_04_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_04_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_07_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_07_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_14_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_14_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_18_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_18_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_07_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_07_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_06_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_06_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_03_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_03_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_02_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_02_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_11_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_11_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_05_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_05_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_03_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_03_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_15_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_15_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_05_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_05_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_18_good();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_18_good();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_17_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_17_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_03_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_03_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_10_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_10_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_16_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_16_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_16_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_16_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_01_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_01_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_17_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_17_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_17_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_17_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_13_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_13_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_02_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_02_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_13_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_13_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_10_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_10_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_02_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_02_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_08_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_08_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_04_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_04_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_14_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_14_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_15_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_15_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_18_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_18_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_16_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_16_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_04_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_04_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_13_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_13_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_12_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_12_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_06_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_06_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_15_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_15_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_06_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_06_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_08_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_08_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_14_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_14_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_01_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_01_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_11_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_11_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_12_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_12_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_11_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_11_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_08_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_08_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_07_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_07_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_05_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_05_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_12_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_12_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_10_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_10_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_09_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_09_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_09_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_09_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_01_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_01_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_09_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_09_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_04_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_04_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_07_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_07_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_14_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_14_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_18_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_18_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_07_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_07_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_06_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_06_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_03_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_03_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_02_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_02_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_11_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_11_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_05_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_05_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_03_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_03_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__int_15_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__int_15_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__short_05_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__short_05_bad();
  printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__char_18_bad();");
  CWE467_Use_of_sizeof_on_Pointer_Type__char_18_bad();
  return 0;
}
// 60B0FC: using guessed type int globalArgc;
// 60B100: using guessed type __int64 globalArgv;

//----- (0000000000401408) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_13_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FIVE == 5 )
  {
    ptr = (__int16 *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 4076F4: using guessed type int GLOBAL_CONST_FIVE;

//----- (0000000000401468) ----------------------------------------------------
void good1()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FIVE == 5 )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 4076F4: using guessed type int GLOBAL_CONST_FIVE;

//----- (00000000004014D4) ----------------------------------------------------
void good2()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FIVE == 5 )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 4076F4: using guessed type int GLOBAL_CONST_FIVE;

//----- (0000000000401534) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_13_good()
{
  good1();
  good2();
}

//----- (000000000040154E) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_10_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( globalTrue )
  {
    ptr = (unsigned int *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 60B0DC: using guessed type int globalTrue;

//----- (00000000004015AC) ----------------------------------------------------
void good1_0()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFalse )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 60B0F8: using guessed type int globalFalse;

//----- (0000000000401616) ----------------------------------------------------
void good2_0()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( globalTrue )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 60B0DC: using guessed type int globalTrue;

//----- (0000000000401674) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_10_good()
{
  good1_0();
  good2_0();
}

//----- (000000000040168E) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_01_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 66;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (00000000004016E3) ----------------------------------------------------
void good1_1()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000401738) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_01_good()
{
  good1_1();
}

//----- (0000000000401748) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_01_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printIntLine(*ptr);
  free(ptr);
}

//----- (000000000040179C) ----------------------------------------------------
void good1_2()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (00000000004017F0) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_01_good()
{
  good1_2();
}

//----- (0000000000401800) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_09_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_TRUE )
  {
    ptr = (__int16 *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 4076EC: using guessed type int GLOBAL_CONST_TRUE;

//----- (000000000040185F) ----------------------------------------------------
void good1_3()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FALSE )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 4076F0: using guessed type int GLOBAL_CONST_FALSE;

//----- (00000000004018CA) ----------------------------------------------------
void good2_1()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_TRUE )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 4076EC: using guessed type int GLOBAL_CONST_TRUE;

//----- (0000000000401929) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_09_good()
{
  good1_3();
  good2_1();
}

//----- (0000000000401943) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_09_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_TRUE )
  {
    ptr = (char *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 66;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 4076EC: using guessed type int GLOBAL_CONST_TRUE;

//----- (00000000004019A2) ----------------------------------------------------
void good1_4()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FALSE )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 4076F0: using guessed type int GLOBAL_CONST_FALSE;

//----- (0000000000401A0D) ----------------------------------------------------
void good2_2()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_TRUE )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 4076EC: using guessed type int GLOBAL_CONST_TRUE;

//----- (0000000000401A6C) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_09_good()
{
  good1_4();
  good2_2();
}

//----- (0000000000401A86) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_03_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000401ADA) ----------------------------------------------------
void good1_5()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000401B2E) ----------------------------------------------------
void good2_3()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000401B82) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_03_good()
{
  good1_5();
  good2_3();
}

//----- (0000000000401B9C) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_14_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFive == 5 )
  {
    ptr = (unsigned int *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 60B0E0: using guessed type int globalFive;

//----- (0000000000401BFB) ----------------------------------------------------
void good1_6()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFive == 5 )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 60B0E0: using guessed type int globalFive;

//----- (0000000000401C66) ----------------------------------------------------
void good2_4()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFive == 5 )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 60B0E0: using guessed type int globalFive;

//----- (0000000000401CC5) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_14_good()
{
  good1_6();
  good2_4();
}

//----- (0000000000401CDF) ----------------------------------------------------
__int64 staticReturnsTrue()
{
  return 1LL;
}

//----- (0000000000401CEA) ----------------------------------------------------
__int64 staticReturnsFalse()
{
  return 0LL;
}

//----- (0000000000401CF5) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_08_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)staticReturnsTrue() )
  {
    ptr = (char *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 66;
    printHexCharLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000401D58) ----------------------------------------------------
void good1_7()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)staticReturnsFalse() )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000401DC7) ----------------------------------------------------
void good2_5()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)staticReturnsTrue() )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000401E2A) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_08_good()
{
  good1_7();
  good2_5();
}

//----- (0000000000401E44) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_14_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFive == 5 )
  {
    ptr = (__int16 *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 60B0E0: using guessed type int globalFive;

//----- (0000000000401EA4) ----------------------------------------------------
void good1_8()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFive == 5 )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 60B0E0: using guessed type int globalFive;

//----- (0000000000401F10) ----------------------------------------------------
void good2_6()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFive == 5 )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 60B0E0: using guessed type int globalFive;

//----- (0000000000401F70) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_14_good()
{
  good1_8();
  good2_6();
}

//----- (0000000000401F8A) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_18_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000401FDF) ----------------------------------------------------
void good1_9()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000402034) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_18_good()
{
  good1_9();
}

//----- (0000000000402044) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_13_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FIVE == 5 )
  {
    ptr = (char *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 66;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 4076F4: using guessed type int GLOBAL_CONST_FIVE;

//----- (00000000004020A4) ----------------------------------------------------
void good1_10()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FIVE == 5 )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 4076F4: using guessed type int GLOBAL_CONST_FIVE;

//----- (0000000000402110) ----------------------------------------------------
void good2_7()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FIVE == 5 )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 4076F4: using guessed type int GLOBAL_CONST_FIVE;

//----- (0000000000402170) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_13_good()
{
  good1_10();
  good2_7();
}

//----- (000000000040218A) ----------------------------------------------------
__int64 staticReturnsTrue_0()
{
  return 1LL;
}

//----- (0000000000402195) ----------------------------------------------------
__int64 staticReturnsFalse_0()
{
  return 0LL;
}

//----- (00000000004021A0) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_08_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)staticReturnsTrue_0() )
  {
    ptr = (__int16 *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printShortLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000402203) ----------------------------------------------------
void good1_11()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)staticReturnsFalse_0() )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000402272) ----------------------------------------------------
void good2_8()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)staticReturnsTrue_0() )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}

//----- (00000000004022D5) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_08_good()
{
  good1_11();
  good2_8();
}

//----- (00000000004022EF) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_09_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_TRUE )
  {
    ptr = (unsigned int *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 4076EC: using guessed type int GLOBAL_CONST_TRUE;

//----- (000000000040234D) ----------------------------------------------------
void good1_12()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FALSE )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 4076F0: using guessed type int GLOBAL_CONST_FALSE;

//----- (00000000004023B7) ----------------------------------------------------
void good2_9()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_TRUE )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 4076EC: using guessed type int GLOBAL_CONST_TRUE;

//----- (0000000000402415) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_09_good()
{
  good1_12();
  good2_9();
}

//----- (000000000040242F) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_12_bad()
{
  unsigned int *v0; // [rsp+0h] [rbp-10h]
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrueOrFalse() )
  {
    ptr = (unsigned int *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printIntLine(*ptr);
    free(ptr);
  }
  else
  {
    v0 = (unsigned int *)malloc(4uLL);
    if ( !v0 )
      exit(-1);
    *v0 = 6;
    printIntLine(*v0);
    free(v0);
  }
}

//----- (00000000004024DD) ----------------------------------------------------
void good1_13()
{
  unsigned int *v0; // [rsp+0h] [rbp-10h]
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrueOrFalse() )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
  else
  {
    v0 = (unsigned int *)malloc(4uLL);
    if ( !v0 )
      exit(-1);
    *v0 = 6;
    printIntLine(*v0);
    free(v0);
  }
}

//----- (000000000040258B) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_12_good()
{
  good1_13();
}

//----- (000000000040259B) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_12_bad()
{
  __int16 *v0; // [rsp+0h] [rbp-10h]
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrueOrFalse() )
  {
    ptr = (__int16 *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printShortLine(*ptr);
    free(ptr);
  }
  else
  {
    v0 = (__int16 *)malloc(2uLL);
    if ( !v0 )
      exit(-1);
    *v0 = 6;
    printShortLine(*v0);
    free(v0);
  }
}

//----- (000000000040264B) ----------------------------------------------------
void good1_14()
{
  __int16 *v0; // [rsp+0h] [rbp-10h]
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrueOrFalse() )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
  else
  {
    v0 = (__int16 *)malloc(2uLL);
    if ( !v0 )
      exit(-1);
    *v0 = 6;
    printShortLine(*v0);
    free(v0);
  }
}

//----- (00000000004026FB) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_12_good()
{
  good1_14();
}

//----- (000000000040270B) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_04_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000402768) ----------------------------------------------------
void good1_15()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (00000000004027D1) ----------------------------------------------------
void good2_10()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (000000000040282E) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_04_good()
{
  good1_15();
  good2_10();
}

//----- (0000000000402848) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_18_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printShortLine(*ptr);
  free(ptr);
}

//----- (000000000040289E) ----------------------------------------------------
void good1_16()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (00000000004028F4) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_18_good()
{
  good1_16();
}

//----- (0000000000402904) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_04_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000402962) ----------------------------------------------------
void good1_17()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (00000000004029CC) ----------------------------------------------------
void good2_11()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000402A2A) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_04_good()
{
  good1_17();
  good2_11();
}

//----- (0000000000402A44) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_03_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 66;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000402A99) ----------------------------------------------------
void good1_18()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000402AEE) ----------------------------------------------------
void good2_12()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000402B43) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_03_good()
{
  good1_18();
  good2_12();
}

//----- (0000000000402B5D) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_17_bad()
{
  unsigned int *ptr; // [rsp+0h] [rbp-10h]
  int i; // [rsp+Ch] [rbp-4h]

  for ( i = 0; i <= 0; ++i )
  {
    ptr = (unsigned int *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printIntLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000402BC4) ----------------------------------------------------
void good1_19()
{
  unsigned int *ptr; // [rsp+0h] [rbp-10h]
  int i; // [rsp+Ch] [rbp-4h]

  for ( i = 0; i <= 0; ++i )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000402C2B) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_17_good()
{
  good1_19();
}

//----- (0000000000402C3B) ----------------------------------------------------
__int64 staticReturnsTrue_1()
{
  return 1LL;
}

//----- (0000000000402C46) ----------------------------------------------------
__int64 staticReturnsFalse_1()
{
  return 0LL;
}

//----- (0000000000402C51) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_08_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)staticReturnsTrue_1() )
  {
    ptr = (unsigned int *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printIntLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000402CB3) ----------------------------------------------------
void good1_20()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)staticReturnsFalse_1() )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000402D21) ----------------------------------------------------
void good2_13()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)staticReturnsTrue_1() )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000402D83) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_08_good()
{
  good1_20();
  good2_13();
}

//----- (0000000000402D9D) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_14_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFive == 5 )
  {
    ptr = (char *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 66;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 60B0E0: using guessed type int globalFive;

//----- (0000000000402DFD) ----------------------------------------------------
void good1_21()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFive == 5 )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 60B0E0: using guessed type int globalFive;

//----- (0000000000402E69) ----------------------------------------------------
void good2_14()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFive == 5 )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 60B0E0: using guessed type int globalFive;

//----- (0000000000402EC9) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_14_good()
{
  good1_21();
  good2_14();
}

//----- (0000000000402EE3) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_17_bad()
{
  __int16 *ptr; // [rsp+0h] [rbp-10h]
  int i; // [rsp+Ch] [rbp-4h]

  for ( i = 0; i <= 0; ++i )
  {
    ptr = (__int16 *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printShortLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000402F4B) ----------------------------------------------------
void good1_22()
{
  __int16 *ptr; // [rsp+0h] [rbp-10h]
  int i; // [rsp+Ch] [rbp-4h]

  for ( i = 0; i <= 0; ++i )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000402FB3) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_17_good()
{
  good1_22();
}

//----- (0000000000402FC3) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_18_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 66;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000403019) ----------------------------------------------------
void good1_23()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (000000000040306F) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_18_good()
{
  good1_23();
}

//----- (000000000040307F) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_07_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFive == 5 )
  {
    ptr = (__int16 *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 60B0C4: using guessed type int staticFive;

//----- (00000000004030DF) ----------------------------------------------------
void good1_24()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFive == 5 )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 60B0C4: using guessed type int staticFive;

//----- (000000000040314B) ----------------------------------------------------
void good2_15()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFive == 5 )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 60B0C4: using guessed type int staticFive;

//----- (00000000004031AB) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_07_good()
{
  good1_24();
  good2_15();
}

//----- (00000000004031C5) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_11_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrue() )
  {
    ptr = (__int16 *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printShortLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000403228) ----------------------------------------------------
void good1_25()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsFalse() )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000403297) ----------------------------------------------------
void good2_16()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrue() )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}

//----- (00000000004032FA) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_11_good()
{
  good1_25();
  good2_16();
}

//----- (0000000000403314) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_02_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000403369) ----------------------------------------------------
void good1_26()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (00000000004033BE) ----------------------------------------------------
void good2_17()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000403413) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_02_good()
{
  good1_26();
  good2_17();
}

//----- (000000000040342D) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_07_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFive_0 == 5 )
  {
    ptr = (char *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 66;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 60B0C8: using guessed type int staticFive_0;

//----- (000000000040348D) ----------------------------------------------------
void good1_27()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFive_0 == 5 )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 60B0C8: using guessed type int staticFive_0;

//----- (00000000004034F9) ----------------------------------------------------
void good2_18()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFive_0 == 5 )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 60B0C8: using guessed type int staticFive_0;

//----- (0000000000403559) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_07_good()
{
  good1_27();
  good2_18();
}

//----- (0000000000403573) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_16_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printIntLine(*ptr);
  free(ptr);
}

//----- (00000000004035C8) ----------------------------------------------------
void good1_28()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (000000000040361D) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_16_good()
{
  good1_28();
}

//----- (000000000040362D) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_16_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000403683) ----------------------------------------------------
void good1_29()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (00000000004036D9) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_16_good()
{
  good1_29();
}

//----- (00000000004036E9) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_12_bad()
{
  char *v0; // [rsp+0h] [rbp-10h]
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrueOrFalse() )
  {
    ptr = (char *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 66;
    printHexCharLine(*ptr);
    free(ptr);
  }
  else
  {
    v0 = (char *)malloc(1uLL);
    if ( !v0 )
      exit(-1);
    *v0 = 71;
    printHexCharLine(*v0);
    free(v0);
  }
}

//----- (0000000000403799) ----------------------------------------------------
void good1_30()
{
  char *v0; // [rsp+0h] [rbp-10h]
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrueOrFalse() )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
  else
  {
    v0 = (char *)malloc(1uLL);
    if ( !v0 )
      exit(-1);
    *v0 = 71;
    printHexCharLine(*v0);
    free(v0);
  }
}

//----- (0000000000403849) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_12_good()
{
  good1_30();
}

//----- (0000000000403859) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_02_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printIntLine(*ptr);
  free(ptr);
}

//----- (00000000004038AD) ----------------------------------------------------
void good1_31()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000403901) ----------------------------------------------------
void good2_19()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000403955) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_02_good()
{
  good1_31();
  good2_19();
}

//----- (000000000040396F) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_10_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( globalTrue )
  {
    ptr = (__int16 *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 60B0DC: using guessed type int globalTrue;

//----- (00000000004039CE) ----------------------------------------------------
void good1_32()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFalse )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 60B0F8: using guessed type int globalFalse;

//----- (0000000000403A39) ----------------------------------------------------
void good2_20()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( globalTrue )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 60B0DC: using guessed type int globalTrue;

//----- (0000000000403A98) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_10_good()
{
  good1_32();
  good2_20();
}

//----- (0000000000403AB2) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_15_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000403B07) ----------------------------------------------------
void good1_33()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000403B5C) ----------------------------------------------------
void good2_21()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000403BB1) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_15_good()
{
  good1_33();
  good2_21();
}

//----- (0000000000403BCB) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_15_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000403C21) ----------------------------------------------------
void good1_34()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000403C77) ----------------------------------------------------
void good2_22()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000403CCD) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_15_good()
{
  good1_34();
  good2_22();
}

//----- (0000000000403CE7) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_11_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrue() )
  {
    ptr = (unsigned int *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printIntLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000403D49) ----------------------------------------------------
void good1_35()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsFalse() )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000403DB7) ----------------------------------------------------
void good2_23()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrue() )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000403E19) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_11_good()
{
  good1_35();
  good2_23();
}

//----- (0000000000403E33) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_07_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFive_1 == 5 )
  {
    ptr = (unsigned int *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 60B0CC: using guessed type int staticFive_1;

//----- (0000000000403E92) ----------------------------------------------------
void good1_36()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFive_1 == 5 )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 60B0CC: using guessed type int staticFive_1;

//----- (0000000000403EFD) ----------------------------------------------------
void good2_24()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFive_1 == 5 )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 60B0CC: using guessed type int staticFive_1;

//----- (0000000000403F5C) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_07_good()
{
  good1_36();
  good2_24();
}

//----- (0000000000403F76) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_04_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 66;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000403FD4) ----------------------------------------------------
void good1_37()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (000000000040403E) ----------------------------------------------------
void good2_25()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (000000000040409C) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_04_good()
{
  good1_37();
  good2_25();
}

//----- (00000000004040B6) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_06_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 66;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000404115) ----------------------------------------------------
void good1_38()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000404180) ----------------------------------------------------
void good2_26()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (00000000004041DF) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_06_good()
{
  good1_38();
  good2_26();
}

//----- (00000000004041F9) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_06_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printIntLine(*ptr);
  free(ptr);
}

//----- (0000000000404257) ----------------------------------------------------
void good1_39()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (00000000004042C1) ----------------------------------------------------
void good2_27()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  ptr = (unsigned int *)malloc(4uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printIntLine(*ptr);
  free(ptr);
}

//----- (000000000040431F) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_06_good()
{
  good1_39();
  good2_27();
}

//----- (0000000000404339) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_01_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printShortLine(*ptr);
  free(ptr);
}

//----- (000000000040438E) ----------------------------------------------------
void good1_40()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (00000000004043E3) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_01_good()
{
  good1_40();
}

//----- (00000000004043F3) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_17_bad()
{
  char *ptr; // [rsp+0h] [rbp-10h]
  int i; // [rsp+Ch] [rbp-4h]

  for ( i = 0; i <= 0; ++i )
  {
    ptr = (char *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 66;
    printHexCharLine(*ptr);
    free(ptr);
  }
}

//----- (000000000040445B) ----------------------------------------------------
void good1_41()
{
  char *ptr; // [rsp+0h] [rbp-10h]
  int i; // [rsp+Ch] [rbp-4h]

  for ( i = 0; i <= 0; ++i )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}

//----- (00000000004044C3) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_17_good()
{
  good1_41();
}

//----- (00000000004044D3) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_05_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( staticTrue )
  {
    ptr = (__int16 *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 60B0D0: using guessed type int staticTrue;

//----- (0000000000404532) ----------------------------------------------------
void good1_42()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFalse )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 60B0EC: using guessed type int staticFalse;

//----- (000000000040459D) ----------------------------------------------------
void good2_28()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  if ( staticTrue )
  {
    ptr = (__int16 *)malloc(2uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printShortLine(*ptr);
    free(ptr);
  }
}
// 60B0D0: using guessed type int staticTrue;

//----- (00000000004045FC) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_05_good()
{
  good1_42();
  good2_28();
}

//----- (0000000000404616) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_11_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrue() )
  {
    ptr = (char *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 66;
    printHexCharLine(*ptr);
    free(ptr);
  }
}

//----- (0000000000404679) ----------------------------------------------------
void good1_43()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsFalse() )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}

//----- (00000000004046E8) ----------------------------------------------------
void good2_29()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( (unsigned int)globalReturnsTrue() )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}

//----- (000000000040474B) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_11_good()
{
  good1_43();
  good2_29();
}

//----- (0000000000404765) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_02_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 66;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (00000000004047BA) ----------------------------------------------------
void good1_44()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (000000000040480F) ----------------------------------------------------
void good2_30()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000404864) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_02_good()
{
  good1_44();
  good2_30();
}

//----- (000000000040487E) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_05_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( staticTrue_0 )
  {
    ptr = (char *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 66;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 60B0D4: using guessed type int staticTrue_0;

//----- (00000000004048DD) ----------------------------------------------------
void good1_45()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFalse_0 )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 60B0F0: using guessed type int staticFalse_0;

//----- (0000000000404948) ----------------------------------------------------
void good2_31()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( staticTrue_0 )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 60B0D4: using guessed type int staticTrue_0;

//----- (00000000004049A7) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_05_good()
{
  good1_45();
  good2_31();
}

//----- (00000000004049C1) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_03_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000404A16) ----------------------------------------------------
void good1_46()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000404A6B) ----------------------------------------------------
void good2_32()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000404AC0) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_03_good()
{
  good1_46();
  good2_32();
}

//----- (0000000000404ADA) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_16_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 66;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000404B30) ----------------------------------------------------
void good1_47()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000404B86) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_16_good()
{
  good1_47();
}

//----- (0000000000404B96) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_10_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( globalTrue )
  {
    ptr = (char *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 66;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 60B0DC: using guessed type int globalTrue;

//----- (0000000000404BF5) ----------------------------------------------------
void good1_48()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( globalFalse )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 60B0F8: using guessed type int globalFalse;

//----- (0000000000404C60) ----------------------------------------------------
void good2_33()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  if ( globalTrue )
  {
    ptr = (char *)malloc(1uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 71;
    printHexCharLine(*ptr);
    free(ptr);
  }
}
// 60B0DC: using guessed type int globalTrue;

//----- (0000000000404CBF) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_10_good()
{
  good1_48();
  good2_33();
}

//----- (0000000000404CD9) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_05_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( staticTrue_1 )
  {
    ptr = (unsigned int *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 60B0D8: using guessed type int staticTrue_1;

//----- (0000000000404D37) ----------------------------------------------------
void good1_49()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( staticFalse_1 )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 60B0F4: using guessed type int staticFalse_1;

//----- (0000000000404DA1) ----------------------------------------------------
void good2_34()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( staticTrue_1 )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 60B0D8: using guessed type int staticTrue_1;

//----- (0000000000404DFF) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_05_good()
{
  good1_49();
  good2_34();
}

//----- (0000000000404E19) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_06_bad()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 5;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000404E78) ----------------------------------------------------
void good1_50()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000404EE3) ----------------------------------------------------
void good2_35()
{
  __int16 *ptr; // [rsp+8h] [rbp-8h]

  ptr = (__int16 *)malloc(2uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 6;
  printShortLine(*ptr);
  free(ptr);
}

//----- (0000000000404F42) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__short_06_good()
{
  good1_50();
  good2_35();
}

//----- (0000000000404F5C) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_15_bad()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(8uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 66;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000404FB2) ----------------------------------------------------
void good1_51()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (0000000000405008) ----------------------------------------------------
void good2_36()
{
  char *ptr; // [rsp+8h] [rbp-8h]

  ptr = (char *)malloc(1uLL);
  if ( !ptr )
    exit(-1);
  *ptr = 71;
  printHexCharLine(*ptr);
  free(ptr);
}

//----- (000000000040505E) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__char_15_good()
{
  good1_51();
  good2_36();
}

//----- (0000000000405078) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_13_bad()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FIVE == 5 )
  {
    ptr = (unsigned int *)malloc(8uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 5;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 4076F4: using guessed type int GLOBAL_CONST_FIVE;

//----- (00000000004050D7) ----------------------------------------------------
void good1_52()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FIVE == 5 )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 4076F4: using guessed type int GLOBAL_CONST_FIVE;

//----- (0000000000405142) ----------------------------------------------------
void good2_37()
{
  unsigned int *ptr; // [rsp+8h] [rbp-8h]

  if ( GLOBAL_CONST_FIVE == 5 )
  {
    ptr = (unsigned int *)malloc(4uLL);
    if ( !ptr )
      exit(-1);
    *ptr = 6;
    printIntLine(*ptr);
    free(ptr);
  }
}
// 4076F4: using guessed type int GLOBAL_CONST_FIVE;

//----- (00000000004051A1) ----------------------------------------------------
void CWE467_Use_of_sizeof_on_Pointer_Type__int_13_good()
{
  good1_52();
  good2_37();
}

//----- (00000000004051BB) ----------------------------------------------------
int __fastcall printLine(const char *a1)
{
  int result; // eax

  if ( a1 )
    result = puts(a1);
  return result;
}

//----- (00000000004051DC) ----------------------------------------------------
int __fastcall printWLine(__int64 a1)
{
  int result; // eax

  if ( a1 )
    result = wprintf("%", a1);
  return result;
}

//----- (0000000000405207) ----------------------------------------------------
int __fastcall printIntLine(unsigned int a1)
{
  return printf("%d\n", a1);
}

//----- (0000000000405228) ----------------------------------------------------
int __fastcall printShortLine(__int16 a1)
{
  return printf("%hd\n", (unsigned int)a1);
}

//----- (000000000040524D) ----------------------------------------------------
int __fastcall printFloatLine(float a1)
{
  return printf("%f\n", a1);
}

//----- (0000000000405273) ----------------------------------------------------
int __fastcall printLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (0000000000405297) ----------------------------------------------------
int __fastcall printLongLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (00000000004052BB) ----------------------------------------------------
int __fastcall printSizeTLine(__int64 a1)
{
  return printf("%zu\n", a1);
}

//----- (00000000004052DF) ----------------------------------------------------
int __fastcall printHexCharLine(char a1)
{
  return printf("%02x\n", (unsigned int)a1);
}

//----- (0000000000405303) ----------------------------------------------------
int __fastcall printWcharLine(int a1)
{
  int v2; // [rsp+10h] [rbp-10h]
  int v3; // [rsp+14h] [rbp-Ch]

  v2 = a1;
  v3 = 0;
  return printf("%ls\n", &v2);
}

//----- (0000000000405333) ----------------------------------------------------
int __fastcall printUnsignedLine(unsigned int a1)
{
  return printf("%u\n", a1);
}

//----- (0000000000405354) ----------------------------------------------------
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1)
{
  return printf("%02x\n", a1);
}

//----- (0000000000405378) ----------------------------------------------------
int __fastcall printDoubleLine(double a1)
{
  return printf("%g\n", a1);
}

//----- (00000000004053A3) ----------------------------------------------------
int __fastcall printStructLine(unsigned int *a1)
{
  return printf("%d -- %d\n", *a1, a1[1]);
}

//----- (00000000004053CF) ----------------------------------------------------
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2)
{
  unsigned __int64 i; // [rsp+18h] [rbp-8h]

  for ( i = 0LL; i < a2; ++i )
    printf("%02x", *(unsigned __int8 *)(a1 + i));
  return puts(s);
}

//----- (0000000000405426) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL;
        i < a2
     && (*__ctype_b_loc())[*(char *)(2 * i + v4)] & 0x1000
     && (*__ctype_b_loc())[*(char *)(2 * i + 1 + v4)] & 0x1000;
        ++i )
  {
    __isoc99_sscanf(2 * i + v4, "%02x", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 400930: using guessed type __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD);

//----- (00000000004054FF) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL; i < a2 && iswxdigit(*(_DWORD *)(8 * i + v4)) && iswxdigit(*(_DWORD *)(8 * i + 4 + v4)); ++i )
  {
    __isoc99_swscanf(8 * i + v4, "%", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 4009F0: using guessed type __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD);

//----- (00000000004055B3) ----------------------------------------------------
__int64 globalReturnsTrue()
{
  return 1LL;
}

//----- (00000000004055BE) ----------------------------------------------------
__int64 globalReturnsFalse()
{
  return 0LL;
}

//----- (00000000004055C9) ----------------------------------------------------
__int64 globalReturnsTrueOrFalse()
{
  return (unsigned int)(rand() % 2);
}

//----- (00000000004055DF) ----------------------------------------------------
void good1_53()
{
  ;
}

//----- (00000000004055E5) ----------------------------------------------------
void good2_38()
{
  ;
}

//----- (00000000004055EB) ----------------------------------------------------
void good3()
{
  ;
}

//----- (00000000004055F1) ----------------------------------------------------
void good4()
{
  ;
}

//----- (00000000004055F7) ----------------------------------------------------
void good5()
{
  ;
}

//----- (00000000004055FD) ----------------------------------------------------
void good6()
{
  ;
}

//----- (0000000000405603) ----------------------------------------------------
void good7()
{
  ;
}

//----- (0000000000405609) ----------------------------------------------------
void good8()
{
  ;
}

//----- (000000000040560F) ----------------------------------------------------
void good9()
{
  ;
}

//----- (0000000000405615) ----------------------------------------------------
void bad1()
{
  ;
}

//----- (000000000040561B) ----------------------------------------------------
void bad2()
{
  ;
}

//----- (0000000000405621) ----------------------------------------------------
void bad3()
{
  ;
}

//----- (0000000000405627) ----------------------------------------------------
void bad4()
{
  ;
}

//----- (000000000040562D) ----------------------------------------------------
void bad5()
{
  ;
}

//----- (0000000000405633) ----------------------------------------------------
void bad6()
{
  ;
}

//----- (0000000000405639) ----------------------------------------------------
void bad7()
{
  ;
}

//----- (000000000040563F) ----------------------------------------------------
void bad8()
{
  ;
}

//----- (0000000000405645) ----------------------------------------------------
void bad9()
{
  ;
}

//----- (000000000040564B) ----------------------------------------------------
void __fastcall __noreturn internal_start(void *a1)
{
  (*((void (__fastcall **)(_QWORD))a1 + 1))(*((_QWORD *)a1 + 2));
  pthread_exit(0LL);
}

//----- (000000000040567E) ----------------------------------------------------
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3)
{
  __int64 result; // rax
  void **v4; // [rsp+8h] [rbp-28h]
  pthread_t newthread; // [rsp+20h] [rbp-10h]
  void *arg; // [rsp+28h] [rbp-8h]

  v4 = a3;
  *a3 = 0LL;
  arg = malloc(0x18uLL);
  if ( !arg )
    return 0LL;
  *((_QWORD *)arg + 1) = a1;
  *((_QWORD *)arg + 2) = a2;
  if ( pthread_create(&newthread, 0LL, (void *(*)(void *))internal_start, arg) )
  {
    free(arg);
    result = 0LL;
  }
  else
  {
    *(_QWORD *)arg = newthread;
    *v4 = arg;
    result = 1LL;
  }
  return result;
}

//----- (0000000000405722) ----------------------------------------------------
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1)
{
  void *thread_return; // [rsp+18h] [rbp-8h]

  return pthread_join(*a1, &thread_return) == 0;
}

//----- (0000000000405756) ----------------------------------------------------
__int64 __fastcall stdThreadDestroy(void *a1)
{
  free(a1);
  return 1LL;
}

//----- (0000000000405775) ----------------------------------------------------
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1)
{
  __int64 result; // rax
  pthread_mutex_t *mutex; // [rsp+18h] [rbp-8h]

  *a1 = 0LL;
  mutex = (pthread_mutex_t *)malloc(0x28uLL);
  if ( !mutex )
    return 0LL;
  if ( pthread_mutex_init(mutex, 0LL) )
  {
    free(a1);
    result = 0LL;
  }
  else
  {
    *a1 = mutex;
    result = 1LL;
  }
  return result;
}

//----- (00000000004057EA) ----------------------------------------------------
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1)
{
  return pthread_mutex_lock(a1);
}

//----- (0000000000405804) ----------------------------------------------------
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1)
{
  return pthread_mutex_unlock(a1);
}

//----- (000000000040581E) ----------------------------------------------------
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1)
{
  pthread_mutex_destroy(a1);
  free(a1);
}

//----- (0000000000405850) ----------------------------------------------------
void _libc_csu_init(void)
{
  __int64 v0; // rbx
  signed __int64 v1; // rbp

  v0 = 0LL;
  v1 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v1 )
  {
    do
      _frame_dummy_init_array_entry[v0++]();
    while ( v0 != v1 );
  }
}
// 60ADD0: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 60ADD8: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (00000000004058C4) ----------------------------------------------------
void term_proc()
{
  ;
}

// ALL OK, 263 function(s) have been successfully decompiled
