/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2018 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
__int64 sub_4008D0();
// int printf(const char *format, ...);
// int puts(const char *s);
// __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD); weak
// void *malloc(size_t size);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int pthread_mutex_init(pthread_mutex_t *mutex, const pthread_mutexattr_t *mutexattr);
// int iswxdigit(wint_t wc);
// void free(void *ptr);
// int pthread_create(pthread_t *newthread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg);
// const unsigned __int16 **__ctype_b_loc(void);
// int pthread_join(pthread_t th, void **thread_return);
// void __noreturn pthread_exit(void *retval);
// int wprintf(const wchar_t *format, ...);
// __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD); weak
// void srand(unsigned int seed);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int rand(void);
// int pthread_mutex_destroy(pthread_mutex_t *mutex);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// time_t time(time_t *timer);
// __int64 _gmon_start__(void); weak
// void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>);
signed __int64 deregister_tm_clones();
__int64 register_tm_clones();
signed __int64 _do_global_dtors_aux();
__int64 frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
char *helperBad();
int CWE562_Return_of_Stack_Variable_Address__return_pointer_buf_01_bad();
char *helperGood1();
int good1();
int CWE562_Return_of_Stack_Variable_Address__return_pointer_buf_01_good();
__int64 *helperBad_0();
int CWE562_Return_of_Stack_Variable_Address__return_buf_01_bad();
char *helperGood1_0();
int good1_0();
int CWE562_Return_of_Stack_Variable_Address__return_buf_01_good();
int __fastcall printLine(const char *a1);
int __fastcall printWLine(__int64 a1);
int __fastcall printIntLine(unsigned int a1);
int __fastcall printShortLine(__int16 a1);
int __fastcall printFloatLine(float a1);
int __fastcall printLongLine(__int64 a1);
int __fastcall printLongLongLine(__int64 a1);
int __fastcall printSizeTLine(__int64 a1);
int __fastcall printHexCharLine(char a1);
int __fastcall printWcharLine(int a1);
int __fastcall printUnsignedLine(unsigned int a1);
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1);
int __fastcall printDoubleLine(double a1);
int __fastcall printStructLine(unsigned int *a1);
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2);
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3);
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3);
__int64 globalReturnsTrue();
__int64 globalReturnsFalse();
__int64 globalReturnsTrueOrFalse();
void good1_1();
void good2();
void good3();
void good4();
void good5();
void good6();
void good7();
void good8();
void good9();
void bad1();
void bad2();
void bad3();
void bad4();
void bad5();
void bad6();
void bad7();
void bad8();
void bad9();
void __fastcall __noreturn internal_start(void *a1);
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3);
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1);
__int64 __fastcall stdThreadDestroy(void *a1);
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1);
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1);
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1);
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

char s[3] = { '\0', '\0', '\0' }; // idb
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_603010)(void) = NULL; // weak
char aElpergood1Stri[18] = "elperGood1 string"; // weak
char charString_3283[19] = "helperGood1 string"; // weak
char completed_6355; // weak
_UNKNOWN unk_603117; // weak
int globalArgc; // weak
__int64 globalArgv; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00000000004008A8) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 400A20: using guessed type __int64 _gmon_start__(void);

//----- (00000000004008D0) ----------------------------------------------------
__int64 sub_4008D0()
{
  return qword_603010();
}
// 603010: using guessed type __int64 (*qword_603010)(void);

//----- (0000000000400A30) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>)
{
  int v2; // esi
  int v3; // [rsp-8h] [rbp-8h]
  __int64 _0; // [rsp+0h] [rbp+0h]

  v2 = v3;
  *(_QWORD *)&v3 = a1;
  __libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v2,
    (char **)&_0,
    _libc_csu_init,
    _libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 400A36: positive sp value 8 has been found

//----- (0000000000400A60) ----------------------------------------------------
signed __int64 deregister_tm_clones()
{
  signed __int64 result; // rax

  result = &unk_603117 - (_UNKNOWN *)&completed_6355;
  if ( (unsigned __int64)(&unk_603117 - (_UNKNOWN *)&completed_6355) > 0xE )
    result = 0LL;
  return result;
}
// 603110: using guessed type char completed_6355;

//----- (0000000000400A90) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (0000000000400AD0) ----------------------------------------------------
signed __int64 _do_global_dtors_aux()
{
  signed __int64 result; // rax

  if ( !completed_6355 )
  {
    result = deregister_tm_clones();
    completed_6355 = 1;
  }
  return result;
}
// 603110: using guessed type char completed_6355;

//----- (0000000000400AF0) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 400AF0: could not find valid save-restore pair for rbp

//----- (0000000000400B1D) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  unsigned int v3; // eax

  v3 = time(0LL);
  srand(v3);
  globalArgc = argc;
  globalArgv = (__int64)argv;
  printLine("Calling CWE562_Return_of_Stack_Variable_Address__return_pointer_buf_01_good();");
  CWE562_Return_of_Stack_Variable_Address__return_pointer_buf_01_good();
  printLine("Calling CWE562_Return_of_Stack_Variable_Address__return_buf_01_good();");
  CWE562_Return_of_Stack_Variable_Address__return_buf_01_good();
  printLine("Calling CWE562_Return_of_Stack_Variable_Address__return_pointer_buf_01_bad();");
  CWE562_Return_of_Stack_Variable_Address__return_pointer_buf_01_bad();
  printLine("Calling CWE562_Return_of_Stack_Variable_Address__return_buf_01_bad();");
  CWE562_Return_of_Stack_Variable_Address__return_buf_01_bad();
  return 0;
}
// 60311C: using guessed type int globalArgc;
// 603120: using guessed type __int64 globalArgv;

//----- (0000000000400BA8) ----------------------------------------------------
char *helperBad()
{
  __int64 v1; // [rsp+0h] [rbp-20h]

  strcpy((char *)&v1, "helperBad string");
  return (char *)&v1 + 1;
}

//----- (0000000000400BDE) ----------------------------------------------------
int CWE562_Return_of_Stack_Variable_Address__return_pointer_buf_01_bad()
{
  char *v0; // rax

  v0 = helperBad();
  return printLine(v0);
}

//----- (0000000000400BF6) ----------------------------------------------------
char *helperGood1()
{
  return aElpergood1Stri;
}

//----- (0000000000400C08) ----------------------------------------------------
int good1()
{
  char *v0; // rax

  v0 = helperGood1();
  return printLine(v0);
}

//----- (0000000000400C20) ----------------------------------------------------
int CWE562_Return_of_Stack_Variable_Address__return_pointer_buf_01_good()
{
  return good1();
}

//----- (0000000000400C30) ----------------------------------------------------
__int64 *helperBad_0()
{
  __int64 v1; // [rsp+0h] [rbp-20h]

  strcpy((char *)&v1, "helperBad string");
  return &v1;
}

//----- (0000000000400C5A) ----------------------------------------------------
int CWE562_Return_of_Stack_Variable_Address__return_buf_01_bad()
{
  __int64 *v0; // rax

  v0 = helperBad_0();
  return printLine((const char *)v0);
}

//----- (0000000000400C72) ----------------------------------------------------
char *helperGood1_0()
{
  return charString_3283;
}

//----- (0000000000400C7D) ----------------------------------------------------
int good1_0()
{
  char *v0; // rax

  v0 = helperGood1_0();
  return printLine(v0);
}

//----- (0000000000400C95) ----------------------------------------------------
int CWE562_Return_of_Stack_Variable_Address__return_buf_01_good()
{
  return good1_0();
}

//----- (0000000000400CA5) ----------------------------------------------------
int __fastcall printLine(const char *a1)
{
  int result; // eax

  if ( a1 )
    result = puts(a1);
  return result;
}

//----- (0000000000400CC6) ----------------------------------------------------
int __fastcall printWLine(__int64 a1)
{
  int result; // eax

  if ( a1 )
    result = wprintf("%", a1);
  return result;
}

//----- (0000000000400CF1) ----------------------------------------------------
int __fastcall printIntLine(unsigned int a1)
{
  return printf("%d\n", a1);
}

//----- (0000000000400D12) ----------------------------------------------------
int __fastcall printShortLine(__int16 a1)
{
  return printf("%hd\n", (unsigned int)a1);
}

//----- (0000000000400D37) ----------------------------------------------------
int __fastcall printFloatLine(float a1)
{
  return printf("%f\n", a1);
}

//----- (0000000000400D5D) ----------------------------------------------------
int __fastcall printLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (0000000000400D81) ----------------------------------------------------
int __fastcall printLongLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (0000000000400DA5) ----------------------------------------------------
int __fastcall printSizeTLine(__int64 a1)
{
  return printf("%zu\n", a1);
}

//----- (0000000000400DC9) ----------------------------------------------------
int __fastcall printHexCharLine(char a1)
{
  return printf("%02x\n", (unsigned int)a1);
}

//----- (0000000000400DED) ----------------------------------------------------
int __fastcall printWcharLine(int a1)
{
  int v2; // [rsp+10h] [rbp-10h]
  int v3; // [rsp+14h] [rbp-Ch]

  v2 = a1;
  v3 = 0;
  return printf("%ls\n", &v2);
}

//----- (0000000000400E1D) ----------------------------------------------------
int __fastcall printUnsignedLine(unsigned int a1)
{
  return printf("%u\n", a1);
}

//----- (0000000000400E3E) ----------------------------------------------------
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1)
{
  return printf("%02x\n", a1);
}

//----- (0000000000400E62) ----------------------------------------------------
int __fastcall printDoubleLine(double a1)
{
  return printf("%g\n", a1);
}

//----- (0000000000400E8D) ----------------------------------------------------
int __fastcall printStructLine(unsigned int *a1)
{
  return printf("%d -- %d\n", *a1, a1[1]);
}

//----- (0000000000400EB9) ----------------------------------------------------
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2)
{
  unsigned __int64 i; // [rsp+18h] [rbp-8h]

  for ( i = 0LL; i < a2; ++i )
    printf("%02x", *(unsigned __int8 *)(a1 + i));
  return puts(s);
}

//----- (0000000000400F10) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL;
        i < a2
     && (*__ctype_b_loc())[*(char *)(2 * i + v4)] & 0x1000
     && (*__ctype_b_loc())[*(char *)(2 * i + 1 + v4)] & 0x1000;
        ++i )
  {
    __isoc99_sscanf(2 * i + v4, "%02x", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 400900: using guessed type __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD);

//----- (0000000000400FE9) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL; i < a2 && iswxdigit(*(_DWORD *)(8 * i + v4)) && iswxdigit(*(_DWORD *)(8 * i + 4 + v4)); ++i )
  {
    __isoc99_swscanf(8 * i + v4, "%", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 4009B0: using guessed type __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD);

//----- (000000000040109D) ----------------------------------------------------
__int64 globalReturnsTrue()
{
  return 1LL;
}

//----- (00000000004010A8) ----------------------------------------------------
__int64 globalReturnsFalse()
{
  return 0LL;
}

//----- (00000000004010B3) ----------------------------------------------------
__int64 globalReturnsTrueOrFalse()
{
  return (unsigned int)(rand() % 2);
}

//----- (00000000004010C9) ----------------------------------------------------
void good1_1()
{
  ;
}

//----- (00000000004010CF) ----------------------------------------------------
void good2()
{
  ;
}

//----- (00000000004010D5) ----------------------------------------------------
void good3()
{
  ;
}

//----- (00000000004010DB) ----------------------------------------------------
void good4()
{
  ;
}

//----- (00000000004010E1) ----------------------------------------------------
void good5()
{
  ;
}

//----- (00000000004010E7) ----------------------------------------------------
void good6()
{
  ;
}

//----- (00000000004010ED) ----------------------------------------------------
void good7()
{
  ;
}

//----- (00000000004010F3) ----------------------------------------------------
void good8()
{
  ;
}

//----- (00000000004010F9) ----------------------------------------------------
void good9()
{
  ;
}

//----- (00000000004010FF) ----------------------------------------------------
void bad1()
{
  ;
}

//----- (0000000000401105) ----------------------------------------------------
void bad2()
{
  ;
}

//----- (000000000040110B) ----------------------------------------------------
void bad3()
{
  ;
}

//----- (0000000000401111) ----------------------------------------------------
void bad4()
{
  ;
}

//----- (0000000000401117) ----------------------------------------------------
void bad5()
{
  ;
}

//----- (000000000040111D) ----------------------------------------------------
void bad6()
{
  ;
}

//----- (0000000000401123) ----------------------------------------------------
void bad7()
{
  ;
}

//----- (0000000000401129) ----------------------------------------------------
void bad8()
{
  ;
}

//----- (000000000040112F) ----------------------------------------------------
void bad9()
{
  ;
}

//----- (0000000000401135) ----------------------------------------------------
void __fastcall __noreturn internal_start(void *a1)
{
  (*((void (__fastcall **)(_QWORD))a1 + 1))(*((_QWORD *)a1 + 2));
  pthread_exit(0LL);
}

//----- (0000000000401168) ----------------------------------------------------
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3)
{
  __int64 result; // rax
  void **v4; // [rsp+8h] [rbp-28h]
  pthread_t newthread; // [rsp+20h] [rbp-10h]
  void *arg; // [rsp+28h] [rbp-8h]

  v4 = a3;
  *a3 = 0LL;
  arg = malloc(0x18uLL);
  if ( !arg )
    return 0LL;
  *((_QWORD *)arg + 1) = a1;
  *((_QWORD *)arg + 2) = a2;
  if ( pthread_create(&newthread, 0LL, (void *(*)(void *))internal_start, arg) )
  {
    free(arg);
    result = 0LL;
  }
  else
  {
    *(_QWORD *)arg = newthread;
    *v4 = arg;
    result = 1LL;
  }
  return result;
}

//----- (000000000040120C) ----------------------------------------------------
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1)
{
  void *thread_return; // [rsp+18h] [rbp-8h]

  return pthread_join(*a1, &thread_return) == 0;
}

//----- (0000000000401240) ----------------------------------------------------
__int64 __fastcall stdThreadDestroy(void *a1)
{
  free(a1);
  return 1LL;
}

//----- (000000000040125F) ----------------------------------------------------
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1)
{
  __int64 result; // rax
  pthread_mutex_t *mutex; // [rsp+18h] [rbp-8h]

  *a1 = 0LL;
  mutex = (pthread_mutex_t *)malloc(0x28uLL);
  if ( !mutex )
    return 0LL;
  if ( pthread_mutex_init(mutex, 0LL) )
  {
    free(a1);
    result = 0LL;
  }
  else
  {
    *a1 = mutex;
    result = 1LL;
  }
  return result;
}

//----- (00000000004012D4) ----------------------------------------------------
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1)
{
  return pthread_mutex_lock(a1);
}

//----- (00000000004012EE) ----------------------------------------------------
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1)
{
  return pthread_mutex_unlock(a1);
}

//----- (0000000000401308) ----------------------------------------------------
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1)
{
  pthread_mutex_destroy(a1);
  free(a1);
}

//----- (0000000000401330) ----------------------------------------------------
void _libc_csu_init(void)
{
  __int64 v0; // rbx
  signed __int64 v1; // rbp

  v0 = 0LL;
  v1 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v1 )
  {
    do
      _frame_dummy_init_array_entry[v0++]();
    while ( v0 != v1 );
  }
}
// 602DD0: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 602DD8: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (00000000004013A4) ----------------------------------------------------
void term_proc()
{
  ;
}

// ALL OK, 66 function(s) have been successfully decompiled
