/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2018 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
__int64 sub_4009B0();
// int printf(const char *format, ...);
// int puts(const char *s);
// __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD); weak
// void *malloc(size_t size);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int pthread_mutex_init(pthread_mutex_t *mutex, const pthread_mutexattr_t *mutexattr);
// char *fgets(char *s, int n, FILE *stream);
// int iswxdigit(wint_t wc);
// void free(void *ptr);
// size_t strlen(const char *s);
// int pthread_create(pthread_t *newthread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg);
// const unsigned __int16 **__ctype_b_loc(void);
// int pthread_join(pthread_t th, void **thread_return);
// void __noreturn pthread_exit(void *retval);
// int wprintf(const wchar_t *format, ...);
// __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD); weak
// int strcmp(const char *s1, const char *s2);
// void srand(unsigned int seed);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int rand(void);
// int pthread_mutex_destroy(pthread_mutex_t *mutex);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// time_t time(time_t *timer);
// __int64 _gmon_start__(void); weak
// void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>);
__int64 deregister_tm_clones();
__int64 register_tm_clones();
__int64 _do_global_dtors_aux();
__int64 frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
int CWE570_Expression_Always_False__global_const_01_bad();
int good1();
int CWE570_Expression_Always_False__global_const_01_good();
int CWE570_Expression_Always_False__string_equals_01_bad();
int good1_0();
int CWE570_Expression_Always_False__string_equals_01_good();
__int64 CWE570_Expression_Always_False__static_const_01_bad();
int good1_1();
int CWE570_Expression_Always_False__static_const_01_good();
void CWE570_Expression_Always_False__two_equals_three_01_bad();
int good1_2();
int CWE570_Expression_Always_False__two_equals_three_01_good();
int CWE570_Expression_Always_False__global_01_bad();
int good1_3();
int CWE570_Expression_Always_False__global_01_good();
int CWE570_Expression_Always_False__static_01_bad();
int good1_4();
int CWE570_Expression_Always_False__static_01_good();
int CWE570_Expression_Always_False__global_return_01_bad();
int good1_5();
int CWE570_Expression_Always_False__global_return_01_good();
void CWE570_Expression_Always_False__n_equal_n_minus_one_01_bad();
int good1_6();
int CWE570_Expression_Always_False__n_equal_n_minus_one_01_good();
int CWE570_Expression_Always_False__global_const_five_01_bad();
int good1_7();
int CWE570_Expression_Always_False__global_const_five_01_good();
void CWE570_Expression_Always_False__zero_01_bad();
int good1_8();
int CWE570_Expression_Always_False__zero_01_good();
__int64 CWE570_Expression_Always_False__unsigned_int_01_bad();
int good1_9();
int CWE570_Expression_Always_False__unsigned_int_01_good();
__int64 staticReturnsFalse();
int CWE570_Expression_Always_False__static_return_01_bad();
int good1_10();
int CWE570_Expression_Always_False__static_return_01_good();
__int64 CWE570_Expression_Always_False__static_const_five_01_bad();
int good1_11();
int CWE570_Expression_Always_False__static_const_five_01_good();
int CWE570_Expression_Always_False__global_five_01_bad();
int good1_12();
int CWE570_Expression_Always_False__global_five_01_good();
int CWE570_Expression_Always_False__static_five_01_bad();
int good1_13();
int CWE570_Expression_Always_False__static_five_01_good();
int CWE570_Expression_Always_False__n_less_int_min_01_bad();
int good1_14();
int CWE570_Expression_Always_False__n_less_int_min_01_good();
int __fastcall printLine(const char *a1);
int __fastcall printWLine(__int64 a1);
int __fastcall printIntLine(unsigned int a1);
int __fastcall printShortLine(__int16 a1);
int __fastcall printFloatLine(float a1);
int __fastcall printLongLine(__int64 a1);
int __fastcall printLongLongLine(__int64 a1);
int __fastcall printSizeTLine(__int64 a1);
int __fastcall printHexCharLine(char a1);
int __fastcall printWcharLine(int a1);
int __fastcall printUnsignedLine(unsigned int a1);
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1);
int __fastcall printDoubleLine(double a1);
int __fastcall printStructLine(unsigned int *a1);
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2);
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3);
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3);
__int64 globalReturnsTrue();
__int64 globalReturnsFalse();
__int64 globalReturnsTrueOrFalse();
void good1_15();
void good2();
void good3();
void good4();
void good5();
void good6();
void good7();
void good8();
void good9();
void bad1();
void bad2();
void bad3();
void bad4();
void bad5();
void bad6();
void bad7();
void bad8();
void bad9();
void __fastcall __noreturn internal_start(void *a1);
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3);
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1);
__int64 __fastcall stdThreadDestroy(void *a1);
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1);
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1);
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1);
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

char s[3] = { '\0', '\0', '\0' }; // idb
int GLOBAL_CONST_FALSE = 0; // weak
int GLOBAL_CONST_FIVE = 5; // weak
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_604010)(void) = NULL; // weak
int staticFive = 5; // weak
int globalFive = 5; // weak
FILE *edata; // idb
char completed_6355; // weak
int staticFalse; // weak
int globalFalse; // weak
int globalArgc; // weak
__int64 globalArgv; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (0000000000400990) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 400B30: using guessed type __int64 _gmon_start__(void);

//----- (00000000004009B0) ----------------------------------------------------
__int64 sub_4009B0()
{
  return qword_604010();
}
// 604010: using guessed type __int64 (*qword_604010)(void);

//----- (0000000000400B40) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>)
{
  int v2; // esi
  int v3; // [rsp-8h] [rbp-8h]
  __int64 _0; // [rsp+0h] [rbp+0h]

  v2 = v3;
  *(_QWORD *)&v3 = a1;
  __libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v2,
    (char **)&_0,
    _libc_csu_init,
    _libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 400B46: positive sp value 8 has been found

//----- (0000000000400B70) ----------------------------------------------------
__int64 deregister_tm_clones()
{
  __int64 result; // rax

  result = 6308071LL - (_QWORD)&edata;
  if ( (unsigned __int64)(6308071LL - (_QWORD)&edata) > 0xE )
    result = 0LL;
  return result;
}

//----- (0000000000400BA0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (0000000000400BE0) ----------------------------------------------------
__int64 _do_global_dtors_aux()
{
  __int64 result; // rax

  if ( !completed_6355 )
  {
    result = deregister_tm_clones();
    completed_6355 = 1;
  }
  return result;
}
// 6040E8: using guessed type char completed_6355;

//----- (0000000000400C00) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 400C00: could not find valid save-restore pair for rbp

//----- (0000000000400C2D) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  unsigned int v3; // eax

  v3 = time(0LL);
  srand(v3);
  globalArgc = argc;
  globalArgv = (__int64)argv;
  printLine("Calling CWE570_Expression_Always_False__static_return_01_good();");
  CWE570_Expression_Always_False__static_return_01_good();
  printLine("Calling CWE570_Expression_Always_False__global_five_01_good();");
  CWE570_Expression_Always_False__global_five_01_good();
  printLine("Calling CWE570_Expression_Always_False__n_equal_n_minus_one_01_good();");
  CWE570_Expression_Always_False__n_equal_n_minus_one_01_good();
  printLine("Calling CWE570_Expression_Always_False__unsigned_int_01_good();");
  CWE570_Expression_Always_False__unsigned_int_01_good();
  printLine("Calling CWE570_Expression_Always_False__static_01_good();");
  CWE570_Expression_Always_False__static_01_good();
  printLine("Calling CWE570_Expression_Always_False__static_const_01_good();");
  CWE570_Expression_Always_False__static_const_01_good();
  printLine("Calling CWE570_Expression_Always_False__n_less_int_min_01_good();");
  CWE570_Expression_Always_False__n_less_int_min_01_good();
  printLine("Calling CWE570_Expression_Always_False__global_const_01_good();");
  CWE570_Expression_Always_False__global_const_01_good();
  printLine("Calling CWE570_Expression_Always_False__string_equals_01_good();");
  CWE570_Expression_Always_False__string_equals_01_good();
  printLine("Calling CWE570_Expression_Always_False__two_equals_three_01_good();");
  CWE570_Expression_Always_False__two_equals_three_01_good();
  printLine("Calling CWE570_Expression_Always_False__global_const_five_01_good();");
  CWE570_Expression_Always_False__global_const_five_01_good();
  printLine("Calling CWE570_Expression_Always_False__static_five_01_good();");
  CWE570_Expression_Always_False__static_five_01_good();
  printLine("Calling CWE570_Expression_Always_False__zero_01_good();");
  CWE570_Expression_Always_False__zero_01_good();
  printLine("Calling CWE570_Expression_Always_False__static_const_five_01_good();");
  CWE570_Expression_Always_False__static_const_five_01_good();
  printLine("Calling CWE570_Expression_Always_False__global_return_01_good();");
  CWE570_Expression_Always_False__global_return_01_good();
  printLine("Calling CWE570_Expression_Always_False__global_01_good();");
  CWE570_Expression_Always_False__global_01_good();
  printLine("Calling CWE570_Expression_Always_False__static_return_01_bad();");
  CWE570_Expression_Always_False__static_return_01_bad();
  printLine("Calling CWE570_Expression_Always_False__global_five_01_bad();");
  CWE570_Expression_Always_False__global_five_01_bad();
  printLine("Calling CWE570_Expression_Always_False__n_equal_n_minus_one_01_bad();");
  CWE570_Expression_Always_False__n_equal_n_minus_one_01_bad();
  printLine("Calling CWE570_Expression_Always_False__unsigned_int_01_bad();");
  CWE570_Expression_Always_False__unsigned_int_01_bad();
  printLine("Calling CWE570_Expression_Always_False__static_01_bad();");
  CWE570_Expression_Always_False__static_01_bad();
  printLine("Calling CWE570_Expression_Always_False__static_const_01_bad();");
  CWE570_Expression_Always_False__static_const_01_bad();
  printLine("Calling CWE570_Expression_Always_False__n_less_int_min_01_bad();");
  CWE570_Expression_Always_False__n_less_int_min_01_bad();
  printLine("Calling CWE570_Expression_Always_False__global_const_01_bad();");
  CWE570_Expression_Always_False__global_const_01_bad();
  printLine("Calling CWE570_Expression_Always_False__string_equals_01_bad();");
  CWE570_Expression_Always_False__string_equals_01_bad();
  printLine("Calling CWE570_Expression_Always_False__two_equals_three_01_bad();");
  CWE570_Expression_Always_False__two_equals_three_01_bad();
  printLine("Calling CWE570_Expression_Always_False__global_const_five_01_bad();");
  CWE570_Expression_Always_False__global_const_five_01_bad();
  printLine("Calling CWE570_Expression_Always_False__static_five_01_bad();");
  CWE570_Expression_Always_False__static_five_01_bad();
  printLine("Calling CWE570_Expression_Always_False__zero_01_bad();");
  CWE570_Expression_Always_False__zero_01_bad();
  printLine("Calling CWE570_Expression_Always_False__static_const_five_01_bad();");
  CWE570_Expression_Always_False__static_const_five_01_bad();
  printLine("Calling CWE570_Expression_Always_False__global_return_01_bad();");
  CWE570_Expression_Always_False__global_return_01_bad();
  printLine("Calling CWE570_Expression_Always_False__global_01_bad();");
  CWE570_Expression_Always_False__global_01_bad();
  return 0;
}
// 6040F4: using guessed type int globalArgc;
// 6040F8: using guessed type __int64 globalArgv;

//----- (0000000000400EE8) ----------------------------------------------------
int CWE570_Expression_Always_False__global_const_01_bad()
{
  int result; // eax

  result = GLOBAL_CONST_FALSE;
  if ( GLOBAL_CONST_FALSE )
    result = printLine("Never prints");
  return result;
}
// 4025C8: using guessed type int GLOBAL_CONST_FALSE;

//----- (0000000000400F02) ----------------------------------------------------
int good1()
{
  int result; // eax

  result = globalReturnsTrueOrFalse();
  if ( result == GLOBAL_CONST_FALSE )
    result = printLine("Sometimes prints");
  return result;
}
// 4025C8: using guessed type int GLOBAL_CONST_FALSE;

//----- (0000000000400F26) ----------------------------------------------------
int CWE570_Expression_Always_False__global_const_01_good()
{
  return good1();
}

//----- (0000000000400F36) ----------------------------------------------------
int CWE570_Expression_Always_False__string_equals_01_bad()
{
  int result; // eax
  char s1[8]; // [rsp+0h] [rbp-10h]
  __int16 v2; // [rsp+8h] [rbp-8h]

  *(_QWORD *)s1 = 435728179558LL;
  v2 = 0;
  result = strcmp(s1, "true");
  if ( !result )
    result = printLine("Never prints");
  return result;
}

//----- (0000000000400F73) ----------------------------------------------------
int good1_0()
{
  int result; // eax
  char s[8]; // [rsp+0h] [rbp-10h]
  __int16 v2; // [rsp+8h] [rbp-8h]
  int v3; // [rsp+Ch] [rbp-4h]

  *(_QWORD *)s = 0LL;
  v2 = 0;
  if ( !fgets(s, 10, edata) )
  {
    printLine("fgets() failed.");
    s[0] = 0;
  }
  v3 = strlen(s);
  if ( v3 > 0 )
    s[v3 - 1] = 0;
  result = strcmp(s, "true");
  if ( !result )
    result = printLine("Sometimes prints");
  return result;
}

//----- (0000000000400FF7) ----------------------------------------------------
int CWE570_Expression_Always_False__string_equals_01_good()
{
  return good1_0();
}

//----- (0000000000401007) ----------------------------------------------------
__int64 CWE570_Expression_Always_False__static_const_01_bad()
{
  return 0LL;
}

//----- (0000000000401020) ----------------------------------------------------
int good1_1()
{
  int result; // eax

  result = globalReturnsTrueOrFalse();
  if ( !result )
    result = printLine("Sometimes prints");
  return result;
}

//----- (0000000000401043) ----------------------------------------------------
int CWE570_Expression_Always_False__static_const_01_good()
{
  return good1_1();
}

//----- (0000000000401053) ----------------------------------------------------
void CWE570_Expression_Always_False__two_equals_three_01_bad()
{
  ;
}

//----- (0000000000401059) ----------------------------------------------------
int good1_2()
{
  int result; // eax

  result = globalReturnsTrueOrFalse();
  if ( result == 1 )
    result = printLine("Sometimes prints");
  return result;
}

//----- (0000000000401078) ----------------------------------------------------
int CWE570_Expression_Always_False__two_equals_three_01_good()
{
  return good1_2();
}

//----- (0000000000401088) ----------------------------------------------------
int CWE570_Expression_Always_False__global_01_bad()
{
  int result; // eax

  result = globalFalse;
  if ( globalFalse )
    result = printLine("Never prints");
  return result;
}
// 6040F0: using guessed type int globalFalse;

//----- (00000000004010A2) ----------------------------------------------------
int good1_3()
{
  int result; // eax

  result = globalReturnsTrueOrFalse();
  if ( result == globalFalse )
    result = printLine("Sometimes prints");
  return result;
}
// 6040F0: using guessed type int globalFalse;

//----- (00000000004010C6) ----------------------------------------------------
int CWE570_Expression_Always_False__global_01_good()
{
  return good1_3();
}

//----- (00000000004010D6) ----------------------------------------------------
int CWE570_Expression_Always_False__static_01_bad()
{
  int result; // eax

  result = staticFalse;
  if ( staticFalse )
    result = printLine("Never prints");
  return result;
}
// 6040EC: using guessed type int staticFalse;

//----- (00000000004010F0) ----------------------------------------------------
int good1_4()
{
  int result; // eax

  result = globalReturnsTrueOrFalse();
  if ( result == staticFalse )
    result = printLine("Sometimes prints");
  return result;
}
// 6040EC: using guessed type int staticFalse;

//----- (0000000000401114) ----------------------------------------------------
int CWE570_Expression_Always_False__static_01_good()
{
  return good1_4();
}

//----- (0000000000401124) ----------------------------------------------------
int CWE570_Expression_Always_False__global_return_01_bad()
{
  int result; // eax

  result = globalReturnsFalse();
  if ( result )
    result = printLine("Never prints");
  return result;
}

//----- (0000000000401142) ----------------------------------------------------
int good1_5()
{
  int v0; // ebx
  int result; // eax

  v0 = globalReturnsTrueOrFalse();
  result = globalReturnsFalse();
  if ( v0 == result )
    result = printLine("Sometimes prints");
  return result;
}

//----- (0000000000401176) ----------------------------------------------------
int CWE570_Expression_Always_False__global_return_01_good()
{
  return good1_5();
}

//----- (0000000000401186) ----------------------------------------------------
void CWE570_Expression_Always_False__n_equal_n_minus_one_01_bad()
{
  ;
}

//----- (0000000000401193) ----------------------------------------------------
int good1_6()
{
  int result; // eax
  int v1; // [rsp+8h] [rbp-8h]
  int v2; // [rsp+Ch] [rbp-4h]

  v2 = rand();
  v1 = rand();
  result = v2;
  if ( v2 != v1 )
    result = printLine("Sometimes prints");
  return result;
}

//----- (00000000004011BF) ----------------------------------------------------
int CWE570_Expression_Always_False__n_equal_n_minus_one_01_good()
{
  return good1_6();
}

//----- (00000000004011CF) ----------------------------------------------------
int CWE570_Expression_Always_False__global_const_five_01_bad()
{
  int result; // eax

  result = GLOBAL_CONST_FIVE;
  if ( GLOBAL_CONST_FIVE != 5 )
    result = printLine("Never prints");
  return result;
}
// 4025CC: using guessed type int GLOBAL_CONST_FIVE;

//----- (00000000004011EA) ----------------------------------------------------
int good1_7()
{
  int v0; // edx
  int result; // eax

  v0 = (unsigned __int64)globalReturnsTrueOrFalse() + 5;
  result = GLOBAL_CONST_FIVE;
  if ( v0 == GLOBAL_CONST_FIVE )
    result = printLine("Sometimes prints");
  return result;
}
// 4025CC: using guessed type int GLOBAL_CONST_FIVE;

//----- (0000000000401211) ----------------------------------------------------
int CWE570_Expression_Always_False__global_const_five_01_good()
{
  return good1_7();
}

//----- (0000000000401221) ----------------------------------------------------
void CWE570_Expression_Always_False__zero_01_bad()
{
  ;
}

//----- (0000000000401227) ----------------------------------------------------
int good1_8()
{
  int result; // eax

  result = globalReturnsTrueOrFalse();
  if ( result )
    result = printLine("Sometimes prints");
  return result;
}

//----- (0000000000401245) ----------------------------------------------------
int CWE570_Expression_Always_False__zero_01_good()
{
  return good1_8();
}

//----- (0000000000401255) ----------------------------------------------------
__int64 CWE570_Expression_Always_False__unsigned_int_01_bad()
{
  return (unsigned int)(2 * rand());
}

//----- (0000000000401269) ----------------------------------------------------
int good1_9()
{
  int result; // eax

  result = rand();
  if ( result <= 1073741822 )
    result = printLine("Sometimes prints");
  return result;
}

//----- (000000000040128E) ----------------------------------------------------
int CWE570_Expression_Always_False__unsigned_int_01_good()
{
  return good1_9();
}

//----- (000000000040129E) ----------------------------------------------------
__int64 staticReturnsFalse()
{
  return 0LL;
}

//----- (00000000004012A9) ----------------------------------------------------
int CWE570_Expression_Always_False__static_return_01_bad()
{
  int result; // eax

  result = staticReturnsFalse();
  if ( result )
    result = printLine("Never prints");
  return result;
}

//----- (00000000004012C7) ----------------------------------------------------
int good1_10()
{
  int v0; // ebx
  int result; // eax

  v0 = globalReturnsTrueOrFalse();
  result = staticReturnsFalse();
  if ( v0 == result )
    result = printLine("Sometimes prints");
  return result;
}

//----- (00000000004012FB) ----------------------------------------------------
int CWE570_Expression_Always_False__static_return_01_good()
{
  return good1_10();
}

//----- (000000000040130B) ----------------------------------------------------
__int64 CWE570_Expression_Always_False__static_const_five_01_bad()
{
  return 5LL;
}

//----- (0000000000401325) ----------------------------------------------------
int good1_11()
{
  int result; // eax

  result = globalReturnsTrueOrFalse();
  if ( !result )
    result = printLine("Sometimes prints");
  return result;
}

//----- (0000000000401343) ----------------------------------------------------
int CWE570_Expression_Always_False__static_const_five_01_good()
{
  return good1_11();
}

//----- (0000000000401353) ----------------------------------------------------
int CWE570_Expression_Always_False__global_five_01_bad()
{
  int result; // eax

  result = globalFive;
  if ( globalFive != 5 )
    result = printLine("Never prints");
  return result;
}
// 6040DC: using guessed type int globalFive;

//----- (000000000040136E) ----------------------------------------------------
int good1_12()
{
  int v0; // edx
  int result; // eax

  v0 = (unsigned __int64)globalReturnsTrueOrFalse() + 5;
  result = globalFive;
  if ( v0 == globalFive )
    result = printLine("Sometimes prints");
  return result;
}
// 6040DC: using guessed type int globalFive;

//----- (0000000000401395) ----------------------------------------------------
int CWE570_Expression_Always_False__global_five_01_good()
{
  return good1_12();
}

//----- (00000000004013A5) ----------------------------------------------------
int CWE570_Expression_Always_False__static_five_01_bad()
{
  int result; // eax

  result = staticFive;
  if ( staticFive != 5 )
    result = printLine("Never prints");
  return result;
}
// 6040D4: using guessed type int staticFive;

//----- (00000000004013C0) ----------------------------------------------------
int good1_13()
{
  int result; // eax

  result = globalReturnsTrueOrFalse();
  if ( !result )
    result = printLine("Sometimes prints");
  return result;
}

//----- (00000000004013DE) ----------------------------------------------------
int CWE570_Expression_Always_False__static_five_01_good()
{
  return good1_13();
}

//----- (00000000004013EE) ----------------------------------------------------
int CWE570_Expression_Always_False__n_less_int_min_01_bad()
{
  return rand();
}

//----- (0000000000401400) ----------------------------------------------------
int good1_14()
{
  int result; // eax

  result = rand();
  if ( result <= 4999 )
    result = printLine("Sometimes prints");
  return result;
}

//----- (0000000000401425) ----------------------------------------------------
int CWE570_Expression_Always_False__n_less_int_min_01_good()
{
  return good1_14();
}

//----- (0000000000401435) ----------------------------------------------------
int __fastcall printLine(const char *a1)
{
  int result; // eax

  if ( a1 )
    result = puts(a1);
  return result;
}

//----- (0000000000401456) ----------------------------------------------------
int __fastcall printWLine(__int64 a1)
{
  int result; // eax

  if ( a1 )
    result = wprintf("%", a1);
  return result;
}

//----- (0000000000401481) ----------------------------------------------------
int __fastcall printIntLine(unsigned int a1)
{
  return printf("%d\n", a1);
}

//----- (00000000004014A2) ----------------------------------------------------
int __fastcall printShortLine(__int16 a1)
{
  return printf("%hd\n", (unsigned int)a1);
}

//----- (00000000004014C7) ----------------------------------------------------
int __fastcall printFloatLine(float a1)
{
  return printf("%f\n", a1);
}

//----- (00000000004014ED) ----------------------------------------------------
int __fastcall printLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (0000000000401511) ----------------------------------------------------
int __fastcall printLongLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (0000000000401535) ----------------------------------------------------
int __fastcall printSizeTLine(__int64 a1)
{
  return printf("%zu\n", a1);
}

//----- (0000000000401559) ----------------------------------------------------
int __fastcall printHexCharLine(char a1)
{
  return printf("%02x\n", (unsigned int)a1);
}

//----- (000000000040157D) ----------------------------------------------------
int __fastcall printWcharLine(int a1)
{
  int v2; // [rsp+10h] [rbp-10h]
  int v3; // [rsp+14h] [rbp-Ch]

  v2 = a1;
  v3 = 0;
  return printf("%ls\n", &v2);
}

//----- (00000000004015AD) ----------------------------------------------------
int __fastcall printUnsignedLine(unsigned int a1)
{
  return printf("%u\n", a1);
}

//----- (00000000004015CE) ----------------------------------------------------
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1)
{
  return printf("%02x\n", a1);
}

//----- (00000000004015F2) ----------------------------------------------------
int __fastcall printDoubleLine(double a1)
{
  return printf("%g\n", a1);
}

//----- (000000000040161D) ----------------------------------------------------
int __fastcall printStructLine(unsigned int *a1)
{
  return printf("%d -- %d\n", *a1, a1[1]);
}

//----- (0000000000401649) ----------------------------------------------------
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2)
{
  unsigned __int64 i; // [rsp+18h] [rbp-8h]

  for ( i = 0LL; i < a2; ++i )
    printf("%02x", *(unsigned __int8 *)(a1 + i));
  return puts(s);
}

//----- (00000000004016A0) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL;
        i < a2
     && (*__ctype_b_loc())[*(char *)(2 * i + v4)] & 0x1000
     && (*__ctype_b_loc())[*(char *)(2 * i + 1 + v4)] & 0x1000;
        ++i )
  {
    __isoc99_sscanf(2 * i + v4, "%02x", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 4009E0: using guessed type __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD);

//----- (0000000000401779) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL; i < a2 && iswxdigit(*(_DWORD *)(8 * i + v4)) && iswxdigit(*(_DWORD *)(8 * i + 4 + v4)); ++i )
  {
    __isoc99_swscanf(8 * i + v4, "%", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 400AB0: using guessed type __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD);

//----- (000000000040182D) ----------------------------------------------------
__int64 globalReturnsTrue()
{
  return 1LL;
}

//----- (0000000000401838) ----------------------------------------------------
__int64 globalReturnsFalse()
{
  return 0LL;
}

//----- (0000000000401843) ----------------------------------------------------
__int64 globalReturnsTrueOrFalse()
{
  return (unsigned int)(rand() % 2);
}

//----- (0000000000401859) ----------------------------------------------------
void good1_15()
{
  ;
}

//----- (000000000040185F) ----------------------------------------------------
void good2()
{
  ;
}

//----- (0000000000401865) ----------------------------------------------------
void good3()
{
  ;
}

//----- (000000000040186B) ----------------------------------------------------
void good4()
{
  ;
}

//----- (0000000000401871) ----------------------------------------------------
void good5()
{
  ;
}

//----- (0000000000401877) ----------------------------------------------------
void good6()
{
  ;
}

//----- (000000000040187D) ----------------------------------------------------
void good7()
{
  ;
}

//----- (0000000000401883) ----------------------------------------------------
void good8()
{
  ;
}

//----- (0000000000401889) ----------------------------------------------------
void good9()
{
  ;
}

//----- (000000000040188F) ----------------------------------------------------
void bad1()
{
  ;
}

//----- (0000000000401895) ----------------------------------------------------
void bad2()
{
  ;
}

//----- (000000000040189B) ----------------------------------------------------
void bad3()
{
  ;
}

//----- (00000000004018A1) ----------------------------------------------------
void bad4()
{
  ;
}

//----- (00000000004018A7) ----------------------------------------------------
void bad5()
{
  ;
}

//----- (00000000004018AD) ----------------------------------------------------
void bad6()
{
  ;
}

//----- (00000000004018B3) ----------------------------------------------------
void bad7()
{
  ;
}

//----- (00000000004018B9) ----------------------------------------------------
void bad8()
{
  ;
}

//----- (00000000004018BF) ----------------------------------------------------
void bad9()
{
  ;
}

//----- (00000000004018C5) ----------------------------------------------------
void __fastcall __noreturn internal_start(void *a1)
{
  (*((void (__fastcall **)(_QWORD))a1 + 1))(*((_QWORD *)a1 + 2));
  pthread_exit(0LL);
}

//----- (00000000004018F8) ----------------------------------------------------
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3)
{
  __int64 result; // rax
  void **v4; // [rsp+8h] [rbp-28h]
  pthread_t newthread; // [rsp+20h] [rbp-10h]
  void *arg; // [rsp+28h] [rbp-8h]

  v4 = a3;
  *a3 = 0LL;
  arg = malloc(0x18uLL);
  if ( !arg )
    return 0LL;
  *((_QWORD *)arg + 1) = a1;
  *((_QWORD *)arg + 2) = a2;
  if ( pthread_create(&newthread, 0LL, (void *(*)(void *))internal_start, arg) )
  {
    free(arg);
    result = 0LL;
  }
  else
  {
    *(_QWORD *)arg = newthread;
    *v4 = arg;
    result = 1LL;
  }
  return result;
}

//----- (000000000040199C) ----------------------------------------------------
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1)
{
  void *thread_return; // [rsp+18h] [rbp-8h]

  return pthread_join(*a1, &thread_return) == 0;
}

//----- (00000000004019D0) ----------------------------------------------------
__int64 __fastcall stdThreadDestroy(void *a1)
{
  free(a1);
  return 1LL;
}

//----- (00000000004019EF) ----------------------------------------------------
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1)
{
  __int64 result; // rax
  pthread_mutex_t *mutex; // [rsp+18h] [rbp-8h]

  *a1 = 0LL;
  mutex = (pthread_mutex_t *)malloc(0x28uLL);
  if ( !mutex )
    return 0LL;
  if ( pthread_mutex_init(mutex, 0LL) )
  {
    free(a1);
    result = 0LL;
  }
  else
  {
    *a1 = mutex;
    result = 1LL;
  }
  return result;
}

//----- (0000000000401A64) ----------------------------------------------------
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1)
{
  return pthread_mutex_lock(a1);
}

//----- (0000000000401A7E) ----------------------------------------------------
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1)
{
  return pthread_mutex_unlock(a1);
}

//----- (0000000000401A98) ----------------------------------------------------
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1)
{
  pthread_mutex_destroy(a1);
  free(a1);
}

//----- (0000000000401AC0) ----------------------------------------------------
void _libc_csu_init(void)
{
  __int64 v0; // rbx
  signed __int64 v1; // rbp

  v0 = 0LL;
  v1 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v1 )
  {
    do
      _frame_dummy_init_array_entry[v0++]();
    while ( v0 != v1 );
  }
}
// 603DD0: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 603DD8: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000401B34) ----------------------------------------------------
void term_proc()
{
  ;
}

// ALL OK, 105 function(s) have been successfully decompiled
