/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2018 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
__int64 sub_400BA0();
// int printf(const char *format, ...);
// void *memset(void *s, int c, size_t n);
// int close(int fd);
// int puts(const char *s);
// uint16_t htons(uint16_t hostshort);
// __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD); weak
// void *malloc(size_t size);
// FILE *fopen(const char *filename, const char *modes);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int pthread_mutex_init(pthread_mutex_t *mutex, const pthread_mutexattr_t *mutexattr);
// char *fgets(char *s, int n, FILE *stream);
// int iswxdigit(wint_t wc);
// void free(void *ptr);
// size_t strlen(const char *s);
// int pthread_create(pthread_t *newthread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg);
// int listen(int fd, int n);
// const unsigned __int16 **__ctype_b_loc(void);
// int pthread_join(pthread_t th, void **thread_return);
// void __noreturn pthread_exit(void *retval);
// int connect(int fd, const struct sockaddr *addr, socklen_t len);
// int socket(int domain, int type, int protocol);
// int wprintf(const wchar_t *format, ...);
// __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD); weak
// ssize_t send(int fd, const void *buf, size_t n, int flags);
// void srand(unsigned int seed);
// int fclose(FILE *stream);
// int bind(int fd, const struct sockaddr *addr, socklen_t len);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int rand(void);
// int pthread_mutex_destroy(pthread_mutex_t *mutex);
// int accept(int fd, struct sockaddr *addr, socklen_t *addr_len);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// time_t time(time_t *timer);
// __int64 _gmon_start__(void); weak
// void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>);
signed __int64 deregister_tm_clones();
__int64 register_tm_clones();
signed __int64 _do_global_dtors_aux();
__int64 frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
void CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_17_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_07_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_11_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_02_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_03_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_16_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_05_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_14_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_05_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_18_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_01_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_10_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_04_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_07_bad();
void CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_17_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_13_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_09_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_09_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_11_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_02_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_03_bad();
__int64 staticReturnsTrue();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_08_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_16_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_06_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_10_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_15_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_15_bad();
__int64 staticReturnsTrue_0();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_08_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_01_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_14_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_18_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_06_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_04_bad();
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_13_bad();
int __fastcall printLine(const char *a1);
int __fastcall printWLine(__int64 a1);
int __fastcall printIntLine(unsigned int a1);
int __fastcall printShortLine(__int16 a1);
int __fastcall printFloatLine(float a1);
int __fastcall printLongLine(__int64 a1);
int __fastcall printLongLongLine(__int64 a1);
int __fastcall printSizeTLine(__int64 a1);
int __fastcall printHexCharLine(char a1);
int __fastcall printWcharLine(int a1);
int __fastcall printUnsignedLine(unsigned int a1);
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1);
int __fastcall printDoubleLine(double a1);
int __fastcall printStructLine(unsigned int *a1);
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2);
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3);
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3);
__int64 globalReturnsTrue();
__int64 globalReturnsFalse();
__int64 globalReturnsTrueOrFalse();
void good1();
void good2();
void good3();
void good4();
void good5();
void good6();
void good7();
void good8();
void good9();
void bad1();
void bad2();
void bad3();
void bad4();
void bad5();
void bad6();
void bad7();
void bad8();
void bad9();
void __fastcall __noreturn internal_start(void *a1);
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3);
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1);
__int64 __fastcall stdThreadDestroy(void *a1);
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1);
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1);
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1);
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

char s[3] = { '\0', '\0', '\0' }; // idb
int GLOBAL_CONST_TRUE = 1; // weak
int GLOBAL_CONST_FIVE = 5; // weak
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_607010)(void) = NULL; // weak
int staticFive = 5; // weak
int staticTrue = 1; // weak
int staticTrue_0 = 1; // weak
int staticFive_0 = 5; // weak
int globalTrue = 1; // weak
int globalFive = 5; // weak
char completed_6355; // weak
_UNKNOWN unk_607147; // weak
int globalArgc; // weak
__int64 globalArgv; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (0000000000400B80) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 400DC0: using guessed type __int64 _gmon_start__(void);

//----- (0000000000400BA0) ----------------------------------------------------
__int64 sub_400BA0()
{
  return qword_607010();
}
// 607010: using guessed type __int64 (*qword_607010)(void);

//----- (0000000000400DD0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>)
{
  int v2; // esi
  int v3; // [rsp-8h] [rbp-8h]
  __int64 _0; // [rsp+0h] [rbp+0h]

  v2 = v3;
  *(_QWORD *)&v3 = a1;
  __libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v2,
    (char **)&_0,
    _libc_csu_init,
    _libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 400DD6: positive sp value 8 has been found

//----- (0000000000400E00) ----------------------------------------------------
signed __int64 deregister_tm_clones()
{
  signed __int64 result; // rax

  result = &unk_607147 - (_UNKNOWN *)&completed_6355;
  if ( (unsigned __int64)(&unk_607147 - (_UNKNOWN *)&completed_6355) > 0xE )
    result = 0LL;
  return result;
}
// 607140: using guessed type char completed_6355;

//----- (0000000000400E30) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (0000000000400E70) ----------------------------------------------------
signed __int64 _do_global_dtors_aux()
{
  signed __int64 result; // rax

  if ( !completed_6355 )
  {
    result = deregister_tm_clones();
    completed_6355 = 1;
  }
  return result;
}
// 607140: using guessed type char completed_6355;

//----- (0000000000400E90) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 400E90: could not find valid save-restore pair for rbp

//----- (0000000000400EBD) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  unsigned int v3; // eax

  v3 = time(0LL);
  srand(v3);
  globalArgc = argc;
  globalArgv = (__int64)argv;
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_01_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_01_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_14_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_14_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_09_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_09_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_06_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_06_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_07_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_07_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_13_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_13_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_04_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_04_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_16_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_16_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_05_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_05_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_11_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_11_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_07_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_07_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_06_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_06_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_09_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_09_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_01_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_01_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_08_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_08_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_13_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_13_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_18_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_18_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_03_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_03_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_02_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_02_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_02_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_02_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_14_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_14_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_08_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_08_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_18_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_18_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_03_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_03_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_05_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_05_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_11_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_11_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_16_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_16_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_17_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_17_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_15_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_15_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_15_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_15_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_17_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_17_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_04_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_04_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_10_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_10_bad();
  printLine("Calling CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_10_bad();");
  CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_10_bad();
  return 0;
}
// 60714C: using guessed type int globalArgc;
// 607150: using guessed type __int64 globalArgv;

//----- (00000000004011A0) ----------------------------------------------------
void CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_17_bad()
{
  size_t v0; // rax
  char s; // [rsp+0h] [rbp-10040h]
  struct sockaddr addr; // [rsp+10000h] [rbp-40h]
  FILE *stream; // [rsp+10018h] [rbp-28h]
  int fd; // [rsp+10024h] [rbp-1Ch]
  int v5; // [rsp+10028h] [rbp-18h]
  int i; // [rsp+1002Ch] [rbp-14h]

  for ( i = 0; i <= 0; ++i )
  {
    fd = -1;
    v5 = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    fd = socket(2, 1, 6);
    if ( fd != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      if ( bind(fd, &addr, 0x10u) != -1 && listen(fd, 5) != -1 )
      {
        v5 = accept(fd, 0LL, 0LL);
        if ( v5 != -1 )
        {
          v0 = strlen(&s);
          send(v5, &s, v0, 0);
          strlen(&s);
        }
      }
    }
    if ( fd != -1 )
      close(fd);
    if ( v5 != -1 )
      close(v5);
  }
}

//----- (0000000000401337) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_07_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  result = staticFive;
  if ( staticFive == 5 )
  {
    fd = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = connect(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        v1 = strlen(&s);
        send(fd, &s, v1, 0);
        result = strlen(&s);
      }
    }
    if ( fd != -1 )
      result = close(fd);
  }
  return result;
}
// 607124: using guessed type int staticFive;

//----- (0000000000401477) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_11_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  result = globalReturnsTrue();
  if ( result )
  {
    fd = -1;
    v6 = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = bind(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        result = listen(fd, 5);
        if ( result != -1 )
        {
          result = accept(fd, 0LL, 0LL);
          v6 = result;
          if ( result != -1 )
          {
            v1 = strlen(&s);
            send(v6, &s, v1, 0);
            result = strlen(&s);
          }
        }
      }
    }
    if ( fd != -1 )
      result = close(fd);
    if ( v6 != -1 )
      result = close(v6);
  }
  return result;
}

//----- (0000000000401606) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_02_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  v6 = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = bind(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      result = listen(fd, 5);
      if ( result != -1 )
      {
        result = accept(fd, 0LL, 0LL);
        v6 = result;
        if ( result != -1 )
        {
          v1 = strlen(&s);
          send(v6, &s, v1, 0);
          result = strlen(&s);
        }
      }
    }
  }
  if ( fd != -1 )
    result = close(fd);
  if ( v6 != -1 )
    result = close(v6);
  return result;
}

//----- (0000000000401783) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_03_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  v6 = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = bind(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      result = listen(fd, 5);
      if ( result != -1 )
      {
        result = accept(fd, 0LL, 0LL);
        v6 = result;
        if ( result != -1 )
        {
          v1 = strlen(&s);
          send(v6, &s, v1, 0);
          result = strlen(&s);
        }
      }
    }
  }
  if ( fd != -1 )
    result = close(fd);
  if ( v6 != -1 )
    result = close(v6);
  return result;
}

//----- (0000000000401900) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_16_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  v6 = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = bind(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      result = listen(fd, 5);
      if ( result != -1 )
      {
        result = accept(fd, 0LL, 0LL);
        v6 = result;
        if ( result != -1 )
        {
          v1 = strlen(&s);
          send(v6, &s, v1, 0);
          result = strlen(&s);
        }
      }
    }
  }
  if ( fd != -1 )
    result = close(fd);
  if ( v6 != -1 )
    result = close(v6);
  return result;
}

//----- (0000000000401A7E) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_05_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  result = staticTrue;
  if ( staticTrue )
  {
    fd = -1;
    v6 = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = bind(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        result = listen(fd, 5);
        if ( result != -1 )
        {
          result = accept(fd, 0LL, 0LL);
          v6 = result;
          if ( result != -1 )
          {
            v1 = strlen(&s);
            send(v6, &s, v1, 0);
            result = strlen(&s);
          }
        }
      }
    }
    if ( fd != -1 )
      result = close(fd);
    if ( v6 != -1 )
      result = close(v6);
  }
  return result;
}
// 607128: using guessed type int staticTrue;

//----- (0000000000401C09) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_14_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  result = globalFive;
  if ( globalFive == 5 )
  {
    fd = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = connect(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        v1 = strlen(&s);
        send(fd, &s, v1, 0);
        result = strlen(&s);
      }
    }
    if ( fd != -1 )
      result = close(fd);
  }
  return result;
}
// 607138: using guessed type int globalFive;

//----- (0000000000401D49) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_05_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  result = staticTrue_0;
  if ( staticTrue_0 )
  {
    fd = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = connect(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        v1 = strlen(&s);
        send(fd, &s, v1, 0);
        result = strlen(&s);
      }
    }
    if ( fd != -1 )
      result = close(fd);
  }
  return result;
}
// 60712C: using guessed type int staticTrue_0;

//----- (0000000000401E88) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_18_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = connect(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      v1 = strlen(&s);
      send(fd, &s, v1, 0);
      result = strlen(&s);
    }
  }
  if ( fd != -1 )
    result = close(fd);
  return result;
}

//----- (0000000000401FBA) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_01_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  v6 = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = bind(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      result = listen(fd, 5);
      if ( result != -1 )
      {
        result = accept(fd, 0LL, 0LL);
        v6 = result;
        if ( result != -1 )
        {
          v1 = strlen(&s);
          send(v6, &s, v1, 0);
          result = strlen(&s);
        }
      }
    }
  }
  if ( fd != -1 )
    result = close(fd);
  if ( v6 != -1 )
    result = close(v6);
  return result;
}

//----- (0000000000402137) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_10_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  result = globalTrue;
  if ( globalTrue )
  {
    fd = -1;
    v6 = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = bind(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        result = listen(fd, 5);
        if ( result != -1 )
        {
          result = accept(fd, 0LL, 0LL);
          v6 = result;
          if ( result != -1 )
          {
            v1 = strlen(&s);
            send(v6, &s, v1, 0);
            result = strlen(&s);
          }
        }
      }
    }
    if ( fd != -1 )
      result = close(fd);
    if ( v6 != -1 )
      result = close(v6);
  }
  return result;
}
// 607134: using guessed type int globalTrue;

//----- (00000000004022C2) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_04_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = connect(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      v1 = strlen(&s);
      send(fd, &s, v1, 0);
      result = strlen(&s);
    }
  }
  if ( fd != -1 )
    result = close(fd);
  return result;
}

//----- (0000000000402400) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_07_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  result = staticFive_0;
  if ( staticFive_0 == 5 )
  {
    fd = -1;
    v6 = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = bind(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        result = listen(fd, 5);
        if ( result != -1 )
        {
          result = accept(fd, 0LL, 0LL);
          v6 = result;
          if ( result != -1 )
          {
            v1 = strlen(&s);
            send(v6, &s, v1, 0);
            result = strlen(&s);
          }
        }
      }
    }
    if ( fd != -1 )
      result = close(fd);
    if ( v6 != -1 )
      result = close(v6);
  }
  return result;
}
// 607130: using guessed type int staticFive_0;

//----- (000000000040258C) ----------------------------------------------------
void CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_17_bad()
{
  size_t v0; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int i; // [rsp+1001Ch] [rbp-14h]

  for ( i = 0; i <= 0; ++i )
  {
    fd = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    fd = socket(2, 1, 6);
    if ( fd != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      if ( connect(fd, &addr, 0x10u) != -1 )
      {
        v0 = strlen(&s);
        send(fd, &s, v0, 0);
        strlen(&s);
      }
    }
    if ( fd != -1 )
      close(fd);
  }
}

//----- (00000000004026D7) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_13_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  result = GLOBAL_CONST_FIVE;
  if ( GLOBAL_CONST_FIVE == 5 )
  {
    fd = -1;
    v6 = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = bind(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        result = listen(fd, 5);
        if ( result != -1 )
        {
          result = accept(fd, 0LL, 0LL);
          v6 = result;
          if ( result != -1 )
          {
            v1 = strlen(&s);
            send(v6, &s, v1, 0);
            result = strlen(&s);
          }
        }
      }
    }
    if ( fd != -1 )
      result = close(fd);
    if ( v6 != -1 )
      result = close(v6);
  }
  return result;
}
// 405664: using guessed type int GLOBAL_CONST_FIVE;

//----- (0000000000402863) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_09_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  result = GLOBAL_CONST_TRUE;
  if ( GLOBAL_CONST_TRUE )
  {
    fd = -1;
    v6 = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = bind(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        result = listen(fd, 5);
        if ( result != -1 )
        {
          result = accept(fd, 0LL, 0LL);
          v6 = result;
          if ( result != -1 )
          {
            v1 = strlen(&s);
            send(v6, &s, v1, 0);
            result = strlen(&s);
          }
        }
      }
    }
    if ( fd != -1 )
      result = close(fd);
    if ( v6 != -1 )
      result = close(v6);
  }
  return result;
}
// 40565C: using guessed type int GLOBAL_CONST_TRUE;

//----- (00000000004029EE) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_09_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  result = GLOBAL_CONST_TRUE;
  if ( GLOBAL_CONST_TRUE )
  {
    fd = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = connect(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        v1 = strlen(&s);
        send(fd, &s, v1, 0);
        result = strlen(&s);
      }
    }
    if ( fd != -1 )
      result = close(fd);
  }
  return result;
}
// 40565C: using guessed type int GLOBAL_CONST_TRUE;

//----- (0000000000402B2D) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_11_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  result = globalReturnsTrue();
  if ( result )
  {
    fd = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = connect(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        v1 = strlen(&s);
        send(fd, &s, v1, 0);
        result = strlen(&s);
      }
    }
    if ( fd != -1 )
      result = close(fd);
  }
  return result;
}

//----- (0000000000402C70) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_02_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = connect(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      v1 = strlen(&s);
      send(fd, &s, v1, 0);
      result = strlen(&s);
    }
  }
  if ( fd != -1 )
    result = close(fd);
  return result;
}

//----- (0000000000402DA1) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_03_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = connect(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      v1 = strlen(&s);
      send(fd, &s, v1, 0);
      result = strlen(&s);
    }
  }
  if ( fd != -1 )
    result = close(fd);
  return result;
}

//----- (0000000000402ED2) ----------------------------------------------------
__int64 staticReturnsTrue()
{
  return 1LL;
}

//----- (0000000000402EDD) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_08_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  result = staticReturnsTrue();
  if ( result )
  {
    fd = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = connect(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        v1 = strlen(&s);
        send(fd, &s, v1, 0);
        result = strlen(&s);
      }
    }
    if ( fd != -1 )
      result = close(fd);
  }
  return result;
}

//----- (0000000000403020) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_16_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = connect(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      v1 = strlen(&s);
      send(fd, &s, v1, 0);
      result = strlen(&s);
    }
  }
  if ( fd != -1 )
    result = close(fd);
  return result;
}

//----- (0000000000403152) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_06_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  v6 = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = bind(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      result = listen(fd, 5);
      if ( result != -1 )
      {
        result = accept(fd, 0LL, 0LL);
        v6 = result;
        if ( result != -1 )
        {
          v1 = strlen(&s);
          send(v6, &s, v1, 0);
          result = strlen(&s);
        }
      }
    }
  }
  if ( fd != -1 )
    result = close(fd);
  if ( v6 != -1 )
    result = close(v6);
  return result;
}

//----- (00000000004032DD) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_10_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  result = globalTrue;
  if ( globalTrue )
  {
    fd = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = connect(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        v1 = strlen(&s);
        send(fd, &s, v1, 0);
        result = strlen(&s);
      }
    }
    if ( fd != -1 )
      result = close(fd);
  }
  return result;
}
// 607134: using guessed type int globalTrue;

//----- (000000000040341C) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_15_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = connect(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      v1 = strlen(&s);
      send(fd, &s, v1, 0);
      result = strlen(&s);
    }
  }
  if ( fd != -1 )
    result = close(fd);
  return result;
}

//----- (000000000040354E) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_15_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  v6 = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = bind(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      result = listen(fd, 5);
      if ( result != -1 )
      {
        result = accept(fd, 0LL, 0LL);
        v6 = result;
        if ( result != -1 )
        {
          v1 = strlen(&s);
          send(v6, &s, v1, 0);
          result = strlen(&s);
        }
      }
    }
  }
  if ( fd != -1 )
    result = close(fd);
  if ( v6 != -1 )
    result = close(v6);
  return result;
}

//----- (00000000004036CC) ----------------------------------------------------
__int64 staticReturnsTrue_0()
{
  return 1LL;
}

//----- (00000000004036D7) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_08_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  result = staticReturnsTrue_0();
  if ( result )
  {
    fd = -1;
    v6 = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = bind(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        result = listen(fd, 5);
        if ( result != -1 )
        {
          result = accept(fd, 0LL, 0LL);
          v6 = result;
          if ( result != -1 )
          {
            v1 = strlen(&s);
            send(v6, &s, v1, 0);
            result = strlen(&s);
          }
        }
      }
    }
    if ( fd != -1 )
      result = close(fd);
    if ( v6 != -1 )
      result = close(v6);
  }
  return result;
}

//----- (0000000000403866) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_01_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = connect(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      v1 = strlen(&s);
      send(fd, &s, v1, 0);
      result = strlen(&s);
    }
  }
  if ( fd != -1 )
    result = close(fd);
  return result;
}

//----- (0000000000403997) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_14_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  result = globalFive;
  if ( globalFive == 5 )
  {
    fd = -1;
    v6 = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = bind(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        result = listen(fd, 5);
        if ( result != -1 )
        {
          result = accept(fd, 0LL, 0LL);
          v6 = result;
          if ( result != -1 )
          {
            v1 = strlen(&s);
            send(v6, &s, v1, 0);
            result = strlen(&s);
          }
        }
      }
    }
    if ( fd != -1 )
      result = close(fd);
    if ( v6 != -1 )
      result = close(v6);
  }
  return result;
}
// 607138: using guessed type int globalFive;

//----- (0000000000403B23) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_18_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  v6 = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = bind(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      result = listen(fd, 5);
      if ( result != -1 )
      {
        result = accept(fd, 0LL, 0LL);
        v6 = result;
        if ( result != -1 )
        {
          v1 = strlen(&s);
          send(v6, &s, v1, 0);
          result = strlen(&s);
        }
      }
    }
  }
  if ( fd != -1 )
    result = close(fd);
  if ( v6 != -1 )
    result = close(v6);
  return result;
}

//----- (0000000000403CA1) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_06_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = connect(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      v1 = strlen(&s);
      send(fd, &s, v1, 0);
      result = strlen(&s);
    }
  }
  if ( fd != -1 )
    result = close(fd);
  return result;
}

//----- (0000000000403DE0) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_listen_socket_04_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+10018h] [rbp-18h]
  int v6; // [rsp+1001Ch] [rbp-14h]

  fd = -1;
  v6 = -1;
  stream = fopen("conf.txt", "r");
  if ( stream )
  {
    if ( !fgets(&s, 0xFFFF, stream) )
    {
      printLine("fgets() failed");
      s = 0;
    }
    fclose(stream);
  }
  result = socket(2, 1, 6);
  fd = result;
  if ( result != -1 )
  {
    memset(&addr, 0, 0x10uLL);
    addr.sa_family = 2;
    *(_DWORD *)&addr.sa_data[2] = 0;
    *(_WORD *)addr.sa_data = htons(0x6987u);
    result = bind(fd, &addr, 0x10u);
    if ( result != -1 )
    {
      result = listen(fd, 5);
      if ( result != -1 )
      {
        result = accept(fd, 0LL, 0LL);
        v6 = result;
        if ( result != -1 )
        {
          v1 = strlen(&s);
          send(v6, &s, v1, 0);
          result = strlen(&s);
        }
      }
    }
  }
  if ( fd != -1 )
    result = close(fd);
  if ( v6 != -1 )
    result = close(v6);
  return result;
}

//----- (0000000000403F6A) ----------------------------------------------------
int CWE506_Embedded_Malicious_Code__file_transfer_connect_socket_13_bad()
{
  int result; // eax
  size_t v1; // rax
  char s; // [rsp+0h] [rbp-10030h]
  struct sockaddr addr; // [rsp+10000h] [rbp-30h]
  FILE *stream; // [rsp+10010h] [rbp-20h]
  int fd; // [rsp+1001Ch] [rbp-14h]

  result = GLOBAL_CONST_FIVE;
  if ( GLOBAL_CONST_FIVE == 5 )
  {
    fd = -1;
    stream = fopen("conf.txt", "r");
    if ( stream )
    {
      if ( !fgets(&s, 0xFFFF, stream) )
      {
        printLine("fgets() failed");
        s = 0;
      }
      fclose(stream);
    }
    result = socket(2, 1, 6);
    fd = result;
    if ( result != -1 )
    {
      memset(&addr, 0, 0x10uLL);
      addr.sa_family = 2;
      *(_DWORD *)&addr.sa_data[2] = 0;
      *(_WORD *)addr.sa_data = htons(0x6987u);
      result = connect(fd, &addr, 0x10u);
      if ( result != -1 )
      {
        v1 = strlen(&s);
        send(fd, &s, v1, 0);
        result = strlen(&s);
      }
    }
    if ( fd != -1 )
      result = close(fd);
  }
  return result;
}
// 405664: using guessed type int GLOBAL_CONST_FIVE;

//----- (00000000004040AA) ----------------------------------------------------
int __fastcall printLine(const char *a1)
{
  int result; // eax

  if ( a1 )
    result = puts(a1);
  return result;
}

//----- (00000000004040CB) ----------------------------------------------------
int __fastcall printWLine(__int64 a1)
{
  int result; // eax

  if ( a1 )
    result = wprintf("%", a1);
  return result;
}

//----- (00000000004040F6) ----------------------------------------------------
int __fastcall printIntLine(unsigned int a1)
{
  return printf("%d\n", a1);
}

//----- (0000000000404117) ----------------------------------------------------
int __fastcall printShortLine(__int16 a1)
{
  return printf("%hd\n", (unsigned int)a1);
}

//----- (000000000040413C) ----------------------------------------------------
int __fastcall printFloatLine(float a1)
{
  return printf("%f\n", a1);
}

//----- (0000000000404162) ----------------------------------------------------
int __fastcall printLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (0000000000404186) ----------------------------------------------------
int __fastcall printLongLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (00000000004041AA) ----------------------------------------------------
int __fastcall printSizeTLine(__int64 a1)
{
  return printf("%zu\n", a1);
}

//----- (00000000004041CE) ----------------------------------------------------
int __fastcall printHexCharLine(char a1)
{
  return printf("%02x\n", (unsigned int)a1);
}

//----- (00000000004041F2) ----------------------------------------------------
int __fastcall printWcharLine(int a1)
{
  int v2; // [rsp+10h] [rbp-10h]
  int v3; // [rsp+14h] [rbp-Ch]

  v2 = a1;
  v3 = 0;
  return printf("%ls\n", &v2);
}

//----- (0000000000404222) ----------------------------------------------------
int __fastcall printUnsignedLine(unsigned int a1)
{
  return printf("%u\n", a1);
}

//----- (0000000000404243) ----------------------------------------------------
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1)
{
  return printf("%02x\n", a1);
}

//----- (0000000000404267) ----------------------------------------------------
int __fastcall printDoubleLine(double a1)
{
  return printf("%g\n", a1);
}

//----- (0000000000404292) ----------------------------------------------------
int __fastcall printStructLine(unsigned int *a1)
{
  return printf("%d -- %d\n", *a1, a1[1]);
}

//----- (00000000004042BE) ----------------------------------------------------
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2)
{
  unsigned __int64 i; // [rsp+18h] [rbp-8h]

  for ( i = 0LL; i < a2; ++i )
    printf("%02x", *(unsigned __int8 *)(a1 + i));
  return puts(s);
}

//----- (0000000000404315) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL;
        i < a2
     && (*__ctype_b_loc())[*(char *)(2 * i + v4)] & 0x1000
     && (*__ctype_b_loc())[*(char *)(2 * i + 1 + v4)] & 0x1000;
        ++i )
  {
    __isoc99_sscanf(2 * i + v4, "%02x", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 400C00: using guessed type __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD);

//----- (00000000004043EE) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL; i < a2 && iswxdigit(*(_DWORD *)(8 * i + v4)) && iswxdigit(*(_DWORD *)(8 * i + 4 + v4)); ++i )
  {
    __isoc99_swscanf(8 * i + v4, "%", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 400D10: using guessed type __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD);

//----- (00000000004044A2) ----------------------------------------------------
__int64 globalReturnsTrue()
{
  return 1LL;
}

//----- (00000000004044AD) ----------------------------------------------------
__int64 globalReturnsFalse()
{
  return 0LL;
}

//----- (00000000004044B8) ----------------------------------------------------
__int64 globalReturnsTrueOrFalse()
{
  return (unsigned int)(rand() % 2);
}

//----- (00000000004044CE) ----------------------------------------------------
void good1()
{
  ;
}

//----- (00000000004044D4) ----------------------------------------------------
void good2()
{
  ;
}

//----- (00000000004044DA) ----------------------------------------------------
void good3()
{
  ;
}

//----- (00000000004044E0) ----------------------------------------------------
void good4()
{
  ;
}

//----- (00000000004044E6) ----------------------------------------------------
void good5()
{
  ;
}

//----- (00000000004044EC) ----------------------------------------------------
void good6()
{
  ;
}

//----- (00000000004044F2) ----------------------------------------------------
void good7()
{
  ;
}

//----- (00000000004044F8) ----------------------------------------------------
void good8()
{
  ;
}

//----- (00000000004044FE) ----------------------------------------------------
void good9()
{
  ;
}

//----- (0000000000404504) ----------------------------------------------------
void bad1()
{
  ;
}

//----- (000000000040450A) ----------------------------------------------------
void bad2()
{
  ;
}

//----- (0000000000404510) ----------------------------------------------------
void bad3()
{
  ;
}

//----- (0000000000404516) ----------------------------------------------------
void bad4()
{
  ;
}

//----- (000000000040451C) ----------------------------------------------------
void bad5()
{
  ;
}

//----- (0000000000404522) ----------------------------------------------------
void bad6()
{
  ;
}

//----- (0000000000404528) ----------------------------------------------------
void bad7()
{
  ;
}

//----- (000000000040452E) ----------------------------------------------------
void bad8()
{
  ;
}

//----- (0000000000404534) ----------------------------------------------------
void bad9()
{
  ;
}

//----- (000000000040453A) ----------------------------------------------------
void __fastcall __noreturn internal_start(void *a1)
{
  (*((void (__fastcall **)(_QWORD))a1 + 1))(*((_QWORD *)a1 + 2));
  pthread_exit(0LL);
}

//----- (000000000040456D) ----------------------------------------------------
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3)
{
  __int64 result; // rax
  void **v4; // [rsp+8h] [rbp-28h]
  pthread_t newthread; // [rsp+20h] [rbp-10h]
  void *arg; // [rsp+28h] [rbp-8h]

  v4 = a3;
  *a3 = 0LL;
  arg = malloc(0x18uLL);
  if ( !arg )
    return 0LL;
  *((_QWORD *)arg + 1) = a1;
  *((_QWORD *)arg + 2) = a2;
  if ( pthread_create(&newthread, 0LL, (void *(*)(void *))internal_start, arg) )
  {
    free(arg);
    result = 0LL;
  }
  else
  {
    *(_QWORD *)arg = newthread;
    *v4 = arg;
    result = 1LL;
  }
  return result;
}

//----- (0000000000404611) ----------------------------------------------------
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1)
{
  void *thread_return; // [rsp+18h] [rbp-8h]

  return pthread_join(*a1, &thread_return) == 0;
}

//----- (0000000000404645) ----------------------------------------------------
__int64 __fastcall stdThreadDestroy(void *a1)
{
  free(a1);
  return 1LL;
}

//----- (0000000000404664) ----------------------------------------------------
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1)
{
  __int64 result; // rax
  pthread_mutex_t *mutex; // [rsp+18h] [rbp-8h]

  *a1 = 0LL;
  mutex = (pthread_mutex_t *)malloc(0x28uLL);
  if ( !mutex )
    return 0LL;
  if ( pthread_mutex_init(mutex, 0LL) )
  {
    free(a1);
    result = 0LL;
  }
  else
  {
    *a1 = mutex;
    result = 1LL;
  }
  return result;
}

//----- (00000000004046D9) ----------------------------------------------------
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1)
{
  return pthread_mutex_lock(a1);
}

//----- (00000000004046F3) ----------------------------------------------------
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1)
{
  return pthread_mutex_unlock(a1);
}

//----- (000000000040470D) ----------------------------------------------------
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1)
{
  pthread_mutex_destroy(a1);
  free(a1);
}

//----- (0000000000404740) ----------------------------------------------------
void _libc_csu_init(void)
{
  __int64 v0; // rbx
  signed __int64 v1; // rbp

  v0 = 0LL;
  v1 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v1 )
  {
    do
      _frame_dummy_init_array_entry[v0++]();
    while ( v0 != v1 );
  }
}
// 606DD0: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 606DD8: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (00000000004047B4) ----------------------------------------------------
void term_proc()
{
  ;
}

// ALL OK, 92 function(s) have been successfully decompiled
