/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2018 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
__int64 sub_400900();
// int printf(const char *format, ...);
// int puts(const char *s);
// __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD); weak
// void *malloc(size_t size);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int pthread_mutex_init(pthread_mutex_t *mutex, const pthread_mutexattr_t *mutexattr);
// int iswxdigit(wint_t wc);
// void free(void *ptr);
// int pthread_create(pthread_t *newthread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg);
// const unsigned __int16 **__ctype_b_loc(void);
// int sprintf(char *s, const char *format, ...);
// int pthread_join(pthread_t th, void **thread_return);
// void __noreturn pthread_exit(void *retval);
// int wprintf(const wchar_t *format, ...);
// __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD); weak
// void srand(unsigned int seed);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int rand(void);
// int pthread_mutex_destroy(pthread_mutex_t *mutex);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// time_t time(time_t *timer);
// __int64 _gmon_start__(void); weak
// void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>);
__int64 deregister_tm_clones();
__int64 register_tm_clones();
__int64 _do_global_dtors_aux();
__int64 frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_10_bad();
int good1();
int good2();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_10_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_07_bad();
int good1_0();
int good2_0();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_07_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_15_bad();
int good1_1();
int good2_1();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_15_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_14_bad();
int good1_2();
int good2_2();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_14_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_04_bad();
int good1_3();
int good2_3();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_04_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_13_bad();
int good1_4();
int good2_4();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_13_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_03_bad();
int good1_5();
int good2_5();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_03_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_01_bad();
int good1_6();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_01_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_18_bad();
int good1_7();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_18_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_05_bad();
int good1_8();
int good2_6();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_05_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_09_bad();
int good1_9();
int good2_7();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_09_good();
__int64 staticReturnsTrue();
__int64 staticReturnsFalse();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_08_bad();
int good1_10();
int good2_8();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_08_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_11_bad();
int good1_11();
int good2_9();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_11_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_02_bad();
int good1_12();
int good2_10();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_02_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_06_bad();
int good1_13();
int good2_11();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_06_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_17_bad();
int good1_14();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_17_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_12_bad();
int good1_15();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_12_good();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_16_bad();
int good1_16();
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_16_good();
int __fastcall printLine(const char *a1);
int __fastcall printWLine(__int64 a1);
int __fastcall printIntLine(unsigned int a1);
int __fastcall printShortLine(__int16 a1);
int __fastcall printFloatLine(float a1);
int __fastcall printLongLine(__int64 a1);
int __fastcall printLongLongLine(__int64 a1);
int __fastcall printSizeTLine(__int64 a1);
int __fastcall printHexCharLine(char a1);
int __fastcall printWcharLine(int a1);
int __fastcall printUnsignedLine(unsigned int a1);
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1);
int __fastcall printDoubleLine(double a1);
int __fastcall printStructLine(unsigned int *a1);
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2);
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3);
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3);
__int64 globalReturnsTrue();
__int64 globalReturnsFalse();
__int64 globalReturnsTrueOrFalse();
void good1_17();
void good2_12();
void good3();
void good4();
void good5();
void good6();
void good7();
void good8();
void good9();
void bad1();
void bad2();
void bad3();
void bad4();
void bad5();
void bad6();
void bad7();
void bad8();
void bad9();
void __fastcall __noreturn internal_start(void *a1);
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3);
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1);
__int64 __fastcall stdThreadDestroy(void *a1);
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1);
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1);
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1);
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

char s[3] = { '\0', '\0', '\0' }; // idb
int GLOBAL_CONST_TRUE = 1; // weak
int GLOBAL_CONST_FALSE = 0; // weak
int GLOBAL_CONST_FIVE = 5; // weak
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_605010)(void) = NULL; // weak
int staticFive = 5; // weak
int staticTrue = 1; // weak
int globalTrue = 1; // weak
int globalFive = 5; // weak
char completed_6355; // weak
int staticFalse; // weak
int globalFalse; // weak
int globalArgc; // weak
__int64 globalArgv; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00000000004008E0) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 400A60: using guessed type __int64 _gmon_start__(void);

//----- (0000000000400900) ----------------------------------------------------
__int64 sub_400900()
{
  return qword_605010();
}
// 605010: using guessed type __int64 (*qword_605010)(void);

//----- (0000000000400A70) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>)
{
  int v2; // esi
  int v3; // [rsp-8h] [rbp-8h]
  __int64 _0; // [rsp+0h] [rbp+0h]

  v2 = v3;
  *(_QWORD *)&v3 = a1;
  __libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v2,
    (char **)&_0,
    _libc_csu_init,
    _libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 400A76: positive sp value 8 has been found

//----- (0000000000400AA0) ----------------------------------------------------
__int64 deregister_tm_clones()
{
  __int64 result; // rax

  result = 6312159LL - (_QWORD)&completed_6355;
  if ( (unsigned __int64)(6312159LL - (_QWORD)&completed_6355) > 0xE )
    result = 0LL;
  return result;
}
// 6050D8: using guessed type char completed_6355;

//----- (0000000000400AD0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (0000000000400B10) ----------------------------------------------------
__int64 _do_global_dtors_aux()
{
  __int64 result; // rax

  if ( !completed_6355 )
  {
    result = deregister_tm_clones();
    completed_6355 = 1;
  }
  return result;
}
// 6050D8: using guessed type char completed_6355;

//----- (0000000000400B30) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 400B30: could not find valid save-restore pair for rbp

//----- (0000000000400B5D) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  unsigned int v3; // eax

  v3 = time(0LL);
  srand(v3);
  globalArgc = argc;
  globalArgv = (__int64)argv;
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_14_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_14_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_18_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_18_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_15_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_15_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_05_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_05_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_13_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_13_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_16_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_16_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_12_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_12_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_09_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_09_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_07_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_07_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_10_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_10_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_08_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_08_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_06_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_06_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_04_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_04_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_11_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_11_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_17_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_17_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_03_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_03_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_02_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_02_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_01_good();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_01_good();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_14_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_14_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_18_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_18_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_15_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_15_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_05_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_05_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_13_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_13_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_16_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_16_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_12_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_12_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_09_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_09_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_07_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_07_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_10_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_10_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_08_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_08_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_06_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_06_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_04_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_04_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_11_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_11_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_17_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_17_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_03_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_03_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_02_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_02_bad();
  printLine("Calling CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_01_bad();");
  CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_01_bad();
  return 0;
}
// 6050E4: using guessed type int globalArgc;
// 6050E8: using guessed type __int64 globalArgv;

//----- (0000000000400E68) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_10_bad()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = globalTrue;
  if ( globalTrue )
  {
    v2 = 5;
    sprintf(&s, "%s", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 6050CC: using guessed type int globalTrue;

//----- (0000000000400EA8) ----------------------------------------------------
int good1()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  if ( globalFalse )
    return printLine("Benign, fixed string");
  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}
// 6050E0: using guessed type int globalFalse;

//----- (0000000000400EF4) ----------------------------------------------------
int good2()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = globalTrue;
  if ( globalTrue )
  {
    v2 = 5;
    sprintf(&s, "%d", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 6050CC: using guessed type int globalTrue;

//----- (0000000000400F34) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_10_good()
{
  good1();
  return good2();
}

//----- (0000000000400F4E) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_07_bad()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = staticFive;
  if ( staticFive == 5 )
  {
    v2 = 5;
    sprintf(&s, "%s", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 6050C4: using guessed type int staticFive;

//----- (0000000000400F8F) ----------------------------------------------------
int good1_0()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  if ( staticFive != 5 )
    return printLine("Benign, fixed string");
  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}
// 6050C4: using guessed type int staticFive;

//----- (0000000000400FDC) ----------------------------------------------------
int good2_0()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = staticFive;
  if ( staticFive == 5 )
  {
    v2 = 5;
    sprintf(&s, "%d", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 6050C4: using guessed type int staticFive;

//----- (000000000040101D) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_07_good()
{
  good1_0();
  return good2_0();
}

//----- (0000000000401037) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_15_bad()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%s", 5LL);
  return printLine(&s);
}

//----- (000000000040106E) ----------------------------------------------------
int good1_1()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (00000000004010A5) ----------------------------------------------------
int good2_1()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (00000000004010DC) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_15_good()
{
  good1_1();
  return good2_1();
}

//----- (00000000004010F6) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_14_bad()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = globalFive;
  if ( globalFive == 5 )
  {
    v2 = 5;
    sprintf(&s, "%s", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 6050D0: using guessed type int globalFive;

//----- (0000000000401137) ----------------------------------------------------
int good1_2()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  if ( globalFive != 5 )
    return printLine("Benign, fixed string");
  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}
// 6050D0: using guessed type int globalFive;

//----- (0000000000401184) ----------------------------------------------------
int good2_2()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = globalFive;
  if ( globalFive == 5 )
  {
    v2 = 5;
    sprintf(&s, "%d", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 6050D0: using guessed type int globalFive;

//----- (00000000004011C5) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_14_good()
{
  good1_2();
  return good2_2();
}

//----- (00000000004011DF) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_04_bad()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%s", 5LL);
  return printLine(&s);
}

//----- (000000000040121E) ----------------------------------------------------
int good1_3()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (0000000000401269) ----------------------------------------------------
int good2_3()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (00000000004012A8) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_04_good()
{
  good1_3();
  return good2_3();
}

//----- (00000000004012C2) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_13_bad()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = GLOBAL_CONST_FIVE;
  if ( GLOBAL_CONST_FIVE == 5 )
  {
    v2 = 5;
    sprintf(&s, "%s", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 40333C: using guessed type int GLOBAL_CONST_FIVE;

//----- (0000000000401303) ----------------------------------------------------
int good1_4()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  if ( GLOBAL_CONST_FIVE != 5 )
    return printLine("Benign, fixed string");
  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}
// 40333C: using guessed type int GLOBAL_CONST_FIVE;

//----- (0000000000401350) ----------------------------------------------------
int good2_4()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = GLOBAL_CONST_FIVE;
  if ( GLOBAL_CONST_FIVE == 5 )
  {
    v2 = 5;
    sprintf(&s, "%d", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 40333C: using guessed type int GLOBAL_CONST_FIVE;

//----- (0000000000401391) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_13_good()
{
  good1_4();
  return good2_4();
}

//----- (00000000004013AB) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_03_bad()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%s", 5LL);
  return printLine(&s);
}

//----- (00000000004013E1) ----------------------------------------------------
int good1_5()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (0000000000401417) ----------------------------------------------------
int good2_5()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (000000000040144D) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_03_good()
{
  good1_5();
  return good2_5();
}

//----- (0000000000401467) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_01_bad()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%s", 5LL);
  return printLine(&s);
}

//----- (000000000040149D) ----------------------------------------------------
int good1_6()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (00000000004014D3) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_01_good()
{
  return good1_6();
}

//----- (00000000004014E3) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_18_bad()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%s", 5LL);
  return printLine(&s);
}

//----- (000000000040151A) ----------------------------------------------------
int good1_7()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (0000000000401551) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_18_good()
{
  return good1_7();
}

//----- (0000000000401561) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_05_bad()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = staticTrue;
  if ( staticTrue )
  {
    v2 = 5;
    sprintf(&s, "%s", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 6050C8: using guessed type int staticTrue;

//----- (00000000004015A1) ----------------------------------------------------
int good1_8()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  if ( staticFalse )
    return printLine("Benign, fixed string");
  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}
// 6050DC: using guessed type int staticFalse;

//----- (00000000004015ED) ----------------------------------------------------
int good2_6()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = staticTrue;
  if ( staticTrue )
  {
    v2 = 5;
    sprintf(&s, "%d", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 6050C8: using guessed type int staticTrue;

//----- (000000000040162D) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_05_good()
{
  good1_8();
  return good2_6();
}

//----- (0000000000401647) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_09_bad()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = GLOBAL_CONST_TRUE;
  if ( GLOBAL_CONST_TRUE )
  {
    v2 = 5;
    sprintf(&s, "%s", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 403334: using guessed type int GLOBAL_CONST_TRUE;

//----- (0000000000401687) ----------------------------------------------------
int good1_9()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  if ( GLOBAL_CONST_FALSE )
    return printLine("Benign, fixed string");
  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}
// 403338: using guessed type int GLOBAL_CONST_FALSE;

//----- (00000000004016D3) ----------------------------------------------------
int good2_7()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = GLOBAL_CONST_TRUE;
  if ( GLOBAL_CONST_TRUE )
  {
    v2 = 5;
    sprintf(&s, "%d", 5LL);
    result = printLine(&s);
  }
  return result;
}
// 403334: using guessed type int GLOBAL_CONST_TRUE;

//----- (0000000000401713) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_09_good()
{
  good1_9();
  return good2_7();
}

//----- (000000000040172D) ----------------------------------------------------
__int64 staticReturnsTrue()
{
  return 1LL;
}

//----- (0000000000401738) ----------------------------------------------------
__int64 staticReturnsFalse()
{
  return 0LL;
}

//----- (0000000000401743) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_08_bad()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = staticReturnsTrue();
  if ( result )
  {
    v2 = 5;
    sprintf(&s, "%s", 5LL);
    result = printLine(&s);
  }
  return result;
}

//----- (0000000000401787) ----------------------------------------------------
int good1_10()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  if ( (unsigned int)staticReturnsFalse() )
    return printLine("Benign, fixed string");
  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (00000000004017D7) ----------------------------------------------------
int good2_8()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = staticReturnsTrue();
  if ( result )
  {
    v2 = 5;
    sprintf(&s, "%d", 5LL);
    result = printLine(&s);
  }
  return result;
}

//----- (000000000040181B) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_08_good()
{
  good1_10();
  return good2_8();
}

//----- (0000000000401835) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_11_bad()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = globalReturnsTrue();
  if ( result )
  {
    v2 = 5;
    sprintf(&s, "%s", 5LL);
    result = printLine(&s);
  }
  return result;
}

//----- (0000000000401879) ----------------------------------------------------
int good1_11()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  if ( (unsigned int)globalReturnsFalse() )
    return printLine("Benign, fixed string");
  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (00000000004018C9) ----------------------------------------------------
int good2_9()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  result = globalReturnsTrue();
  if ( result )
  {
    v2 = 5;
    sprintf(&s, "%d", 5LL);
    result = printLine(&s);
  }
  return result;
}

//----- (000000000040190D) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_11_good()
{
  good1_11();
  return good2_9();
}

//----- (0000000000401927) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_02_bad()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%s", 5LL);
  return printLine(&s);
}

//----- (000000000040195D) ----------------------------------------------------
int good1_12()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (0000000000401993) ----------------------------------------------------
int good2_10()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (00000000004019C9) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_02_good()
{
  good1_12();
  return good2_10();
}

//----- (00000000004019E3) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_06_bad()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%s", 5LL);
  return printLine(&s);
}

//----- (0000000000401A23) ----------------------------------------------------
int good1_13()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (0000000000401A6F) ----------------------------------------------------
int good2_11()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (0000000000401AAF) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_06_good()
{
  good1_13();
  return good2_11();
}

//----- (0000000000401AC9) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_17_bad()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+68h] [rbp-8h]
  int i; // [rsp+6Ch] [rbp-4h]

  for ( i = 0; i <= 0; ++i )
  {
    v2 = 5;
    sprintf(&s, "%s", 5LL);
    result = printLine(&s);
  }
  return result;
}

//----- (0000000000401B12) ----------------------------------------------------
int good1_14()
{
  int result; // eax
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+68h] [rbp-8h]
  int i; // [rsp+6Ch] [rbp-4h]

  for ( i = 0; i <= 0; ++i )
  {
    v2 = 5;
    sprintf(&s, "%d", 5LL);
    result = printLine(&s);
  }
  return result;
}

//----- (0000000000401B5B) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_17_good()
{
  return good1_14();
}

//----- (0000000000401B6B) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_12_bad()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+68h] [rbp-8h]
  int v3; // [rsp+6Ch] [rbp-4h]

  if ( (unsigned int)globalReturnsTrueOrFalse() )
  {
    v3 = 5;
    sprintf(&s, "%s", 5LL);
  }
  else
  {
    v2 = 5;
    sprintf(&s, "%d", 5LL);
  }
  return printLine(&s);
}

//----- (0000000000401BDD) ----------------------------------------------------
int good1_15()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+68h] [rbp-8h]
  int v3; // [rsp+6Ch] [rbp-4h]

  if ( (unsigned int)globalReturnsTrueOrFalse() )
    v3 = 5;
  else
    v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (0000000000401C4F) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_12_good()
{
  return good1_15();
}

//----- (0000000000401C5F) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_16_bad()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%s", 5LL);
  return printLine(&s);
}

//----- (0000000000401C96) ----------------------------------------------------
int good1_16()
{
  char s; // [rsp+0h] [rbp-70h]
  int v2; // [rsp+6Ch] [rbp-4h]

  v2 = 5;
  sprintf(&s, "%d", 5LL);
  return printLine(&s);
}

//----- (0000000000401CCD) ----------------------------------------------------
int CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument__basic_16_good()
{
  return good1_16();
}

//----- (0000000000401CDD) ----------------------------------------------------
int __fastcall printLine(const char *a1)
{
  int result; // eax

  if ( a1 )
    result = puts(a1);
  return result;
}

//----- (0000000000401CFE) ----------------------------------------------------
int __fastcall printWLine(__int64 a1)
{
  int result; // eax

  if ( a1 )
    result = wprintf("%", a1);
  return result;
}

//----- (0000000000401D29) ----------------------------------------------------
int __fastcall printIntLine(unsigned int a1)
{
  return printf("%d\n", a1);
}

//----- (0000000000401D4A) ----------------------------------------------------
int __fastcall printShortLine(__int16 a1)
{
  return printf("%hd\n", (unsigned int)a1);
}

//----- (0000000000401D6F) ----------------------------------------------------
int __fastcall printFloatLine(float a1)
{
  return printf("%f\n", a1);
}

//----- (0000000000401D95) ----------------------------------------------------
int __fastcall printLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (0000000000401DB9) ----------------------------------------------------
int __fastcall printLongLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (0000000000401DDD) ----------------------------------------------------
int __fastcall printSizeTLine(__int64 a1)
{
  return printf("%zu\n", a1);
}

//----- (0000000000401E01) ----------------------------------------------------
int __fastcall printHexCharLine(char a1)
{
  return printf("%02x\n", (unsigned int)a1);
}

//----- (0000000000401E25) ----------------------------------------------------
int __fastcall printWcharLine(int a1)
{
  int v2; // [rsp+10h] [rbp-10h]
  int v3; // [rsp+14h] [rbp-Ch]

  v2 = a1;
  v3 = 0;
  return printf("%ls\n", &v2);
}

//----- (0000000000401E55) ----------------------------------------------------
int __fastcall printUnsignedLine(unsigned int a1)
{
  return printf("%u\n", a1);
}

//----- (0000000000401E76) ----------------------------------------------------
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1)
{
  return printf("%02x\n", a1);
}

//----- (0000000000401E9A) ----------------------------------------------------
int __fastcall printDoubleLine(double a1)
{
  return printf("%g\n", a1);
}

//----- (0000000000401EC5) ----------------------------------------------------
int __fastcall printStructLine(unsigned int *a1)
{
  return printf("%d -- %d\n", *a1, a1[1]);
}

//----- (0000000000401EF1) ----------------------------------------------------
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2)
{
  unsigned __int64 i; // [rsp+18h] [rbp-8h]

  for ( i = 0LL; i < a2; ++i )
    printf("%02x", *(unsigned __int8 *)(a1 + i));
  return puts(s);
}

//----- (0000000000401F48) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL;
        i < a2
     && (*__ctype_b_loc())[*(char *)(2 * i + v4)] & 0x1000
     && (*__ctype_b_loc())[*(char *)(2 * i + 1 + v4)] & 0x1000;
        ++i )
  {
    __isoc99_sscanf(2 * i + v4, "%02x", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 400930: using guessed type __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD);

//----- (0000000000402021) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL; i < a2 && iswxdigit(*(_DWORD *)(8 * i + v4)) && iswxdigit(*(_DWORD *)(8 * i + 4 + v4)); ++i )
  {
    __isoc99_swscanf(8 * i + v4, "%", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 4009F0: using guessed type __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD);

//----- (00000000004020D5) ----------------------------------------------------
__int64 globalReturnsTrue()
{
  return 1LL;
}

//----- (00000000004020E0) ----------------------------------------------------
__int64 globalReturnsFalse()
{
  return 0LL;
}

//----- (00000000004020EB) ----------------------------------------------------
__int64 globalReturnsTrueOrFalse()
{
  return (unsigned int)(rand() % 2);
}

//----- (0000000000402101) ----------------------------------------------------
void good1_17()
{
  ;
}

//----- (0000000000402107) ----------------------------------------------------
void good2_12()
{
  ;
}

//----- (000000000040210D) ----------------------------------------------------
void good3()
{
  ;
}

//----- (0000000000402113) ----------------------------------------------------
void good4()
{
  ;
}

//----- (0000000000402119) ----------------------------------------------------
void good5()
{
  ;
}

//----- (000000000040211F) ----------------------------------------------------
void good6()
{
  ;
}

//----- (0000000000402125) ----------------------------------------------------
void good7()
{
  ;
}

//----- (000000000040212B) ----------------------------------------------------
void good8()
{
  ;
}

//----- (0000000000402131) ----------------------------------------------------
void good9()
{
  ;
}

//----- (0000000000402137) ----------------------------------------------------
void bad1()
{
  ;
}

//----- (000000000040213D) ----------------------------------------------------
void bad2()
{
  ;
}

//----- (0000000000402143) ----------------------------------------------------
void bad3()
{
  ;
}

//----- (0000000000402149) ----------------------------------------------------
void bad4()
{
  ;
}

//----- (000000000040214F) ----------------------------------------------------
void bad5()
{
  ;
}

//----- (0000000000402155) ----------------------------------------------------
void bad6()
{
  ;
}

//----- (000000000040215B) ----------------------------------------------------
void bad7()
{
  ;
}

//----- (0000000000402161) ----------------------------------------------------
void bad8()
{
  ;
}

//----- (0000000000402167) ----------------------------------------------------
void bad9()
{
  ;
}

//----- (000000000040216D) ----------------------------------------------------
void __fastcall __noreturn internal_start(void *a1)
{
  (*((void (__fastcall **)(_QWORD))a1 + 1))(*((_QWORD *)a1 + 2));
  pthread_exit(0LL);
}

//----- (00000000004021A0) ----------------------------------------------------
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3)
{
  __int64 result; // rax
  void **v4; // [rsp+8h] [rbp-28h]
  pthread_t newthread; // [rsp+20h] [rbp-10h]
  void *arg; // [rsp+28h] [rbp-8h]

  v4 = a3;
  *a3 = 0LL;
  arg = malloc(0x18uLL);
  if ( !arg )
    return 0LL;
  *((_QWORD *)arg + 1) = a1;
  *((_QWORD *)arg + 2) = a2;
  if ( pthread_create(&newthread, 0LL, (void *(*)(void *))internal_start, arg) )
  {
    free(arg);
    result = 0LL;
  }
  else
  {
    *(_QWORD *)arg = newthread;
    *v4 = arg;
    result = 1LL;
  }
  return result;
}

//----- (0000000000402244) ----------------------------------------------------
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1)
{
  void *thread_return; // [rsp+18h] [rbp-8h]

  return pthread_join(*a1, &thread_return) == 0;
}

//----- (0000000000402278) ----------------------------------------------------
__int64 __fastcall stdThreadDestroy(void *a1)
{
  free(a1);
  return 1LL;
}

//----- (0000000000402297) ----------------------------------------------------
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1)
{
  __int64 result; // rax
  pthread_mutex_t *mutex; // [rsp+18h] [rbp-8h]

  *a1 = 0LL;
  mutex = (pthread_mutex_t *)malloc(0x28uLL);
  if ( !mutex )
    return 0LL;
  if ( pthread_mutex_init(mutex, 0LL) )
  {
    free(a1);
    result = 0LL;
  }
  else
  {
    *a1 = mutex;
    result = 1LL;
  }
  return result;
}

//----- (000000000040230C) ----------------------------------------------------
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1)
{
  return pthread_mutex_lock(a1);
}

//----- (0000000000402326) ----------------------------------------------------
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1)
{
  return pthread_mutex_unlock(a1);
}

//----- (0000000000402340) ----------------------------------------------------
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1)
{
  pthread_mutex_destroy(a1);
  free(a1);
}

//----- (0000000000402370) ----------------------------------------------------
void _libc_csu_init(void)
{
  __int64 v0; // rbx
  signed __int64 v1; // rbp

  v0 = 0LL;
  v1 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v1 )
  {
    do
      _frame_dummy_init_array_entry[v0++]();
    while ( v0 != v1 );
  }
}
// 604DD0: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 604DD8: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (00000000004023E4) ----------------------------------------------------
void term_proc()
{
  ;
}

// ALL OK, 125 function(s) have been successfully decompiled
