/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2018 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
__int64 sub_400900();
// int printf(const char *format, ...);
// int puts(const char *s);
// __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD); weak
// void __noreturn exit(int status);
// void *malloc(size_t size);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int pthread_mutex_init(pthread_mutex_t *mutex, const pthread_mutexattr_t *mutexattr);
// int iswxdigit(wint_t wc);
// void free(void *ptr);
// int pthread_create(pthread_t *newthread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg);
// const unsigned __int16 **__ctype_b_loc(void);
// int pthread_join(pthread_t th, void **thread_return);
// void __noreturn pthread_exit(void *retval);
// int wprintf(const wchar_t *format, ...);
// __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD); weak
// void srand(unsigned int seed);
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int rand(void);
// int pthread_mutex_destroy(pthread_mutex_t *mutex);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// time_t time(time_t *timer);
// __int64 _gmon_start__(void); weak
// void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>);
signed __int64 deregister_tm_clones();
__int64 register_tm_clones();
signed __int64 _do_global_dtors_aux();
__int64 frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_bad();
void good1();
void good2();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_bad();
void good1_0();
void good2_0();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_bad();
void good1_1();
void good2_1();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_bad();
void good1_2();
void good2_2();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_bad();
void good1_3();
void good2_3();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_good();
__int64 staticReturnsTrue();
__int64 staticReturnsFalse();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_bad();
void good1_4();
void good2_4();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_bad();
void good1_5();
void good2_5();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_bad();
void good1_6();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_bad();
void good1_7();
void good2_6();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_bad();
void good1_8();
void good2_7();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_bad();
void good1_9();
void good2_8();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_bad();
void good1_10();
void good2_9();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_bad();
void good1_11();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_bad();
void good1_12();
void good2_10();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_bad();
void good1_13();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_bad();
void good1_14();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_bad();
void good1_15();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_good();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_bad();
void good1_16();
void good2_11();
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_good();
int __fastcall printLine(const char *a1);
int __fastcall printWLine(__int64 a1);
int __fastcall printIntLine(unsigned int a1);
int __fastcall printShortLine(__int16 a1);
int __fastcall printFloatLine(float a1);
int __fastcall printLongLine(__int64 a1);
int __fastcall printLongLongLine(__int64 a1);
int __fastcall printSizeTLine(__int64 a1);
int __fastcall printHexCharLine(char a1);
int __fastcall printWcharLine(int a1);
int __fastcall printUnsignedLine(unsigned int a1);
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1);
int __fastcall printDoubleLine(double a1);
int __fastcall printStructLine(unsigned int *a1);
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2);
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3);
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3);
__int64 globalReturnsTrue();
__int64 globalReturnsFalse();
__int64 globalReturnsTrueOrFalse();
void good1_17();
void good2_12();
void good3();
void good4();
void good5();
void good6();
void good7();
void good8();
void good9();
void bad1();
void bad2();
void bad3();
void bad4();
void bad5();
void bad6();
void bad7();
void bad8();
void bad9();
void __fastcall __noreturn internal_start(void *a1);
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3);
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1);
__int64 __fastcall stdThreadDestroy(void *a1);
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1);
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1);
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1);
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

char s[3] = { '\0', '\0', '\0' }; // idb
int GLOBAL_CONST_TRUE = 1; // weak
int GLOBAL_CONST_FALSE = 0; // weak
int GLOBAL_CONST_FIVE = 5; // weak
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_606010)(void) = NULL; // weak
int staticFive = 5; // weak
int staticTrue = 1; // weak
int globalTrue = 1; // weak
int globalFive = 5; // weak
char completed_6355; // weak
_UNKNOWN unk_6060DF; // weak
__int64 badLock_3301; // weak
__int64 goodLock_3304; // weak
__int64 goodLock_3307; // weak
__int64 badLock_3301_0; // weak
__int64 goodLock_3309; // weak
__int64 goodLock_3313; // weak
__int64 badLock_3300; // weak
__int64 goodLock_3303; // weak
__int64 goodLock_3306; // weak
int staticFalse; // weak
__int64 badLock_3302; // weak
__int64 goodLock_3305; // weak
__int64 goodLock_3308; // weak
__int64 badLock_3300_0; // weak
__int64 goodLock_3303_0; // weak
__int64 goodLock_3306_0; // weak
__int64 badLock_3304; // weak
__int64 goodLock_3307_0; // weak
__int64 goodLock_3310; // weak
__int64 badLock_3300_1; // weak
__int64 goodLock_3303_1; // weak
__int64 goodLock_3306_1; // weak
__int64 badLock_3300_2; // weak
__int64 goodLock_3303_2; // weak
__int64 badLock_3300_3; // weak
__int64 goodLock_3303_3; // weak
__int64 goodLock_3306_2; // weak
__int64 badLock_3300_4; // weak
__int64 goodLock_3303_4; // weak
__int64 goodLock_3306_3; // weak
__int64 badLock_3300_5; // weak
__int64 goodLock_3303_5; // weak
__int64 goodLock_3306_4; // weak
__int64 badLock_3301_1; // weak
__int64 goodLock_3304_0; // weak
__int64 goodLock_3307_1; // weak
__int64 badLock_3301_2; // weak
__int64 goodLock_3308_0; // weak
__int64 badLock_3302_0; // weak
__int64 goodLock_3305_0; // weak
__int64 goodLock_3308_1; // weak
__int64 badLock_3301_3; // weak
__int64 goodLock_3305_1; // weak
__int64 badLock_3300_6; // weak
__int64 goodLock_3301; // weak
__int64 goodLock_3304_1; // weak
__int64 goodLock_3305_2; // weak
__int64 badLock_3300_7; // weak
__int64 goodLock_3305_3; // weak
__int64 badLock_3300_8; // weak
__int64 goodLock_3303_6; // weak
__int64 goodLock_3306_5; // weak
int globalFalse; // weak
int globalArgc; // weak
__int64 globalArgv; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00000000004008D8) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 400A60: using guessed type __int64 _gmon_start__(void);

//----- (0000000000400900) ----------------------------------------------------
__int64 sub_400900()
{
  return qword_606010();
}
// 606010: using guessed type __int64 (*qword_606010)(void);

//----- (0000000000400A70) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>)
{
  int v2; // esi
  int v3; // [rsp-8h] [rbp-8h]
  __int64 _0; // [rsp+0h] [rbp+0h]

  v2 = v3;
  *(_QWORD *)&v3 = a1;
  __libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v2,
    (char **)&_0,
    _libc_csu_init,
    _libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 400A76: positive sp value 8 has been found

//----- (0000000000400AA0) ----------------------------------------------------
signed __int64 deregister_tm_clones()
{
  signed __int64 result; // rax

  result = &unk_6060DF - (_UNKNOWN *)&completed_6355;
  if ( (unsigned __int64)(&unk_6060DF - (_UNKNOWN *)&completed_6355) > 0xE )
    result = 0LL;
  return result;
}
// 6060D8: using guessed type char completed_6355;

//----- (0000000000400AD0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (0000000000400B10) ----------------------------------------------------
signed __int64 _do_global_dtors_aux()
{
  signed __int64 result; // rax

  if ( !completed_6355 )
  {
    result = deregister_tm_clones();
    completed_6355 = 1;
  }
  return result;
}
// 6060D8: using guessed type char completed_6355;

//----- (0000000000400B30) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 400B30: could not find valid save-restore pair for rbp

//----- (0000000000400B5D) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  unsigned int v3; // eax

  v3 = time(0LL);
  srand(v3);
  globalArgc = argc;
  globalArgv = (__int64)argv;
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_good();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_good();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_bad();
  printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_bad();");
  CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_bad();
  return 0;
}
// 606284: using guessed type int globalArgc;
// 606288: using guessed type __int64 globalArgv;

//----- (0000000000400E68) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_bad()
{
  if ( staticFive == 5 )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3301) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)badLock_3301);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)badLock_3301);
  }
}
// 6060C4: using guessed type int staticFive;
// 6060E0: using guessed type __int64 badLock_3301;

//----- (0000000000400ED7) ----------------------------------------------------
void good1()
{
  if ( staticFive == 5 )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3304) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3304);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3304);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3304);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 6060C4: using guessed type int staticFive;
// 6060E8: using guessed type __int64 goodLock_3304;

//----- (0000000000400F6B) ----------------------------------------------------
void good2()
{
  if ( staticFive == 5 )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3307) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3307);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3307);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3307);
  }
}
// 6060C4: using guessed type int staticFive;
// 6060F0: using guessed type __int64 goodLock_3307;

//----- (0000000000400FF3) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_good()
{
  good1();
  good2();
}

//----- (000000000040100D) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_bad()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3301_0) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)badLock_3301_0);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)badLock_3301_0);
}
// 6060F8: using guessed type __int64 badLock_3301_0;

//----- (0000000000401072) ----------------------------------------------------
void good1_0()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3309) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3309);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3309);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3309);
}
// 606100: using guessed type __int64 goodLock_3309;

//----- (00000000004010F0) ----------------------------------------------------
void good2_0()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3313) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3313);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3313);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3313);
}
// 606108: using guessed type __int64 goodLock_3313;

//----- (000000000040116E) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_good()
{
  good1_0();
  good2_0();
}

//----- (0000000000401188) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_bad()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3300) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)badLock_3300);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)badLock_3300);
}
// 606110: using guessed type __int64 badLock_3300;

//----- (00000000004011EC) ----------------------------------------------------
void good1_1()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3303) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3303);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3303);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3303);
}
// 606118: using guessed type __int64 goodLock_3303;

//----- (0000000000401269) ----------------------------------------------------
void good2_1()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3306) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3306);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3306);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3306);
}
// 606120: using guessed type __int64 goodLock_3306;

//----- (00000000004012E6) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_good()
{
  good1_1();
  good2_1();
}

//----- (0000000000401300) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_bad()
{
  if ( staticTrue )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3302) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)badLock_3302);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)badLock_3302);
  }
}
// 6060C8: using guessed type int staticTrue;
// 606130: using guessed type __int64 badLock_3302;

//----- (000000000040136E) ----------------------------------------------------
void good1_2()
{
  if ( staticFalse )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3305) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3305);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3305);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3305);
  }
}
// 606128: using guessed type int staticFalse;
// 606138: using guessed type __int64 goodLock_3305;

//----- (0000000000401401) ----------------------------------------------------
void good2_2()
{
  if ( staticTrue )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3308) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3308);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3308);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3308);
  }
}
// 6060C8: using guessed type int staticTrue;
// 606140: using guessed type __int64 goodLock_3308;

//----- (0000000000401488) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_good()
{
  good1_2();
  good2_2();
}

//----- (00000000004014A2) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_bad()
{
  if ( globalFive == 5 )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3300_0) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)badLock_3300_0);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)badLock_3300_0);
  }
}
// 6060D0: using guessed type int globalFive;
// 606148: using guessed type __int64 badLock_3300_0;

//----- (0000000000401511) ----------------------------------------------------
void good1_3()
{
  if ( globalFive == 5 )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3303_0) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3303_0);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3303_0);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3303_0);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 6060D0: using guessed type int globalFive;
// 606150: using guessed type __int64 goodLock_3303_0;

//----- (00000000004015A5) ----------------------------------------------------
void good2_3()
{
  if ( globalFive == 5 )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3306_0) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3306_0);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3306_0);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3306_0);
  }
}
// 6060D0: using guessed type int globalFive;
// 606158: using guessed type __int64 goodLock_3306_0;

//----- (000000000040162D) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_good()
{
  good1_3();
  good2_3();
}

//----- (0000000000401647) ----------------------------------------------------
__int64 staticReturnsTrue()
{
  return 1LL;
}

//----- (0000000000401652) ----------------------------------------------------
__int64 staticReturnsFalse()
{
  return 0LL;
}

//----- (000000000040165D) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_bad()
{
  if ( (unsigned int)staticReturnsTrue() )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3304) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)badLock_3304);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)badLock_3304);
  }
}
// 606160: using guessed type __int64 badLock_3304;

//----- (00000000004016CF) ----------------------------------------------------
void good1_4()
{
  if ( (unsigned int)staticReturnsFalse() )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3307_0) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3307_0);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3307_0);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3307_0);
  }
}
// 606168: using guessed type __int64 goodLock_3307_0;

//----- (0000000000401766) ----------------------------------------------------
void good2_4()
{
  if ( (unsigned int)staticReturnsTrue() )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3310) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3310);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3310);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3310);
  }
}
// 606170: using guessed type __int64 goodLock_3310;

//----- (00000000004017F1) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_good()
{
  good1_4();
  good2_4();
}

//----- (000000000040180B) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_bad()
{
  if ( GLOBAL_CONST_FIVE == 5 )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3300_1) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)badLock_3300_1);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)badLock_3300_1);
  }
}
// 404278: using guessed type int GLOBAL_CONST_FIVE;
// 606178: using guessed type __int64 badLock_3300_1;

//----- (000000000040187A) ----------------------------------------------------
void good1_5()
{
  if ( GLOBAL_CONST_FIVE == 5 )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3303_1) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3303_1);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3303_1);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3303_1);
  }
  else
  {
    printLine("Benign, fixed string");
  }
}
// 404278: using guessed type int GLOBAL_CONST_FIVE;
// 606180: using guessed type __int64 goodLock_3303_1;

//----- (000000000040190E) ----------------------------------------------------
void good2_5()
{
  if ( GLOBAL_CONST_FIVE == 5 )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3306_1) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3306_1);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3306_1);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3306_1);
  }
}
// 404278: using guessed type int GLOBAL_CONST_FIVE;
// 606188: using guessed type __int64 goodLock_3306_1;

//----- (0000000000401996) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_good()
{
  good1_5();
  good2_5();
}

//----- (00000000004019B0) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_bad()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3300_2) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)badLock_3300_2);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)badLock_3300_2);
}
// 606190: using guessed type __int64 badLock_3300_2;

//----- (0000000000401A14) ----------------------------------------------------
void good1_6()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3303_2) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3303_2);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3303_2);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3303_2);
}
// 606198: using guessed type __int64 goodLock_3303_2;

//----- (0000000000401A91) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_good()
{
  good1_6();
}

//----- (0000000000401AA1) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_bad()
{
  if ( GLOBAL_CONST_TRUE )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3300_3) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)badLock_3300_3);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)badLock_3300_3);
  }
}
// 404270: using guessed type int GLOBAL_CONST_TRUE;
// 6061A0: using guessed type __int64 badLock_3300_3;

//----- (0000000000401B0F) ----------------------------------------------------
void good1_7()
{
  if ( GLOBAL_CONST_FALSE )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3303_3) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3303_3);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3303_3);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3303_3);
  }
}
// 404274: using guessed type int GLOBAL_CONST_FALSE;
// 6061A8: using guessed type __int64 goodLock_3303_3;

//----- (0000000000401BA2) ----------------------------------------------------
void good2_6()
{
  if ( GLOBAL_CONST_TRUE )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3306_2) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3306_2);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3306_2);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3306_2);
  }
}
// 404270: using guessed type int GLOBAL_CONST_TRUE;
// 6061B0: using guessed type __int64 goodLock_3306_2;

//----- (0000000000401C29) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_good()
{
  good1_7();
  good2_6();
}

//----- (0000000000401C43) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_bad()
{
  if ( (unsigned int)globalReturnsTrue() )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3300_4) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)badLock_3300_4);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)badLock_3300_4);
  }
}
// 6061B8: using guessed type __int64 badLock_3300_4;

//----- (0000000000401CB5) ----------------------------------------------------
void good1_8()
{
  if ( (unsigned int)globalReturnsFalse() )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3303_4) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3303_4);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3303_4);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3303_4);
  }
}
// 6061C0: using guessed type __int64 goodLock_3303_4;

//----- (0000000000401D4C) ----------------------------------------------------
void good2_7()
{
  if ( (unsigned int)globalReturnsTrue() )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3306_3) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3306_3);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3306_3);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3306_3);
  }
}
// 6061C8: using guessed type __int64 goodLock_3306_3;

//----- (0000000000401DD7) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_good()
{
  good1_8();
  good2_7();
}

//----- (0000000000401DF1) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_bad()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3300_5) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)badLock_3300_5);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)badLock_3300_5);
}
// 6061D0: using guessed type __int64 badLock_3300_5;

//----- (0000000000401E55) ----------------------------------------------------
void good1_9()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3303_5) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3303_5);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3303_5);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3303_5);
}
// 6061D8: using guessed type __int64 goodLock_3303_5;

//----- (0000000000401ED2) ----------------------------------------------------
void good2_8()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3306_4) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3306_4);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3306_4);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3306_4);
}
// 6061E0: using guessed type __int64 goodLock_3306_4;

//----- (0000000000401F4F) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_good()
{
  good1_9();
  good2_8();
}

//----- (0000000000401F69) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_bad()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3301_1) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)badLock_3301_1);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)badLock_3301_1);
}
// 6061E8: using guessed type __int64 badLock_3301_1;

//----- (0000000000401FD7) ----------------------------------------------------
void good1_10()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3304_0) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3304_0);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3304_0);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3304_0);
}
// 6061F0: using guessed type __int64 goodLock_3304_0;

//----- (000000000040206A) ----------------------------------------------------
void good2_9()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3307_1) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3307_1);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3307_1);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3307_1);
}
// 6061F8: using guessed type __int64 goodLock_3307_1;

//----- (00000000004020F1) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_good()
{
  good1_10();
  good2_9();
}

//----- (000000000040210B) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_bad()
{
  int i; // [rsp+Ch] [rbp-4h]

  for ( i = 0; i <= 0; ++i )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3301_2) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)badLock_3301_2);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)badLock_3301_2);
  }
}
// 606200: using guessed type __int64 badLock_3301_2;

//----- (0000000000402186) ----------------------------------------------------
void good1_11()
{
  int i; // [rsp+Ch] [rbp-4h]

  for ( i = 0; i <= 0; ++i )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3308_0) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3308_0);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3308_0);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3308_0);
  }
}
// 606208: using guessed type __int64 goodLock_3308_0;

//----- (000000000040221E) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_good()
{
  good1_11();
}

//----- (000000000040222E) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_bad()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3302_0) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)badLock_3302_0);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)badLock_3302_0);
}
// 606210: using guessed type __int64 badLock_3302_0;

//----- (000000000040229B) ----------------------------------------------------
void good1_12()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3305_0) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3305_0);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3305_0);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3305_0);
}
// 606218: using guessed type __int64 goodLock_3305_0;

//----- (000000000040232D) ----------------------------------------------------
void good2_10()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3308_1) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3308_1);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3308_1);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3308_1);
}
// 606220: using guessed type __int64 goodLock_3308_1;

//----- (00000000004023B3) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_good()
{
  good1_12();
  good2_10();
}

//----- (00000000004023CD) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_bad()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3301_3) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)badLock_3301_3);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)badLock_3301_3);
}
// 606228: using guessed type __int64 badLock_3301_3;

//----- (0000000000402432) ----------------------------------------------------
void good1_13()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3305_1) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3305_1);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3305_1);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3305_1);
}
// 606230: using guessed type __int64 goodLock_3305_1;

//----- (00000000004024B0) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_good()
{
  good1_13();
}

//----- (00000000004024C0) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_bad()
{
  if ( (unsigned int)globalReturnsTrueOrFalse() )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3300_6) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)badLock_3300_6);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)badLock_3300_6);
  }
  else
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3301) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3301);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3301);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3301);
  }
}
// 606238: using guessed type __int64 badLock_3300_6;
// 606240: using guessed type __int64 goodLock_3301;

//----- (00000000004025AB) ----------------------------------------------------
void good1_14()
{
  if ( (unsigned int)globalReturnsTrueOrFalse() )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3304_1) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3304_1);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3304_1);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3304_1);
  }
  else
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3305_2) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3305_2);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3305_2);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3305_2);
  }
}
// 606248: using guessed type __int64 goodLock_3304_1;
// 606250: using guessed type __int64 goodLock_3305_2;

//----- (00000000004026AF) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_good()
{
  good1_14();
}

//----- (00000000004026BF) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_bad()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3300_7) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)badLock_3300_7);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)badLock_3300_7);
}
// 606258: using guessed type __int64 badLock_3300_7;

//----- (0000000000402724) ----------------------------------------------------
void good1_15()
{
  printLine("Creating lock...");
  if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3305_3) )
  {
    printLine("Could not create lock");
    exit(1);
  }
  printLine("Acquiring lock...");
  stdThreadLockAcquire((pthread_mutex_t *)goodLock_3305_3);
  printLine("Releasing lock...");
  stdThreadLockRelease((pthread_mutex_t *)goodLock_3305_3);
  printLine("Destroying lock...");
  stdThreadLockDestroy((pthread_mutex_t *)goodLock_3305_3);
}
// 606260: using guessed type __int64 goodLock_3305_3;

//----- (00000000004027A2) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_good()
{
  good1_15();
}

//----- (00000000004027B2) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_bad()
{
  if ( globalTrue )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&badLock_3300_8) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)badLock_3300_8);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)badLock_3300_8);
  }
}
// 6060CC: using guessed type int globalTrue;
// 606268: using guessed type __int64 badLock_3300_8;

//----- (0000000000402820) ----------------------------------------------------
void good1_16()
{
  if ( globalFalse )
  {
    printLine("Benign, fixed string");
  }
  else
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3303_6) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3303_6);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3303_6);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3303_6);
  }
}
// 606270: using guessed type __int64 goodLock_3303_6;
// 606280: using guessed type int globalFalse;

//----- (00000000004028B3) ----------------------------------------------------
void good2_11()
{
  if ( globalTrue )
  {
    printLine("Creating lock...");
    if ( !(unsigned int)stdThreadLockCreate((pthread_mutex_t **)&goodLock_3306_5) )
    {
      printLine("Could not create lock");
      exit(1);
    }
    printLine("Acquiring lock...");
    stdThreadLockAcquire((pthread_mutex_t *)goodLock_3306_5);
    printLine("Releasing lock...");
    stdThreadLockRelease((pthread_mutex_t *)goodLock_3306_5);
    printLine("Destroying lock...");
    stdThreadLockDestroy((pthread_mutex_t *)goodLock_3306_5);
  }
}
// 6060CC: using guessed type int globalTrue;
// 606278: using guessed type __int64 goodLock_3306_5;

//----- (000000000040293A) ----------------------------------------------------
void CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_good()
{
  good1_16();
  good2_11();
}

//----- (0000000000402954) ----------------------------------------------------
int __fastcall printLine(const char *a1)
{
  int result; // eax

  if ( a1 )
    result = puts(a1);
  return result;
}

//----- (0000000000402975) ----------------------------------------------------
int __fastcall printWLine(__int64 a1)
{
  int result; // eax

  if ( a1 )
    result = wprintf("%", a1);
  return result;
}

//----- (00000000004029A0) ----------------------------------------------------
int __fastcall printIntLine(unsigned int a1)
{
  return printf("%d\n", a1);
}

//----- (00000000004029C1) ----------------------------------------------------
int __fastcall printShortLine(__int16 a1)
{
  return printf("%hd\n", (unsigned int)a1);
}

//----- (00000000004029E6) ----------------------------------------------------
int __fastcall printFloatLine(float a1)
{
  return printf("%f\n", a1);
}

//----- (0000000000402A0C) ----------------------------------------------------
int __fastcall printLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (0000000000402A30) ----------------------------------------------------
int __fastcall printLongLongLine(__int64 a1)
{
  return printf("%ld\n", a1);
}

//----- (0000000000402A54) ----------------------------------------------------
int __fastcall printSizeTLine(__int64 a1)
{
  return printf("%zu\n", a1);
}

//----- (0000000000402A78) ----------------------------------------------------
int __fastcall printHexCharLine(char a1)
{
  return printf("%02x\n", (unsigned int)a1);
}

//----- (0000000000402A9C) ----------------------------------------------------
int __fastcall printWcharLine(int a1)
{
  int v2; // [rsp+10h] [rbp-10h]
  int v3; // [rsp+14h] [rbp-Ch]

  v2 = a1;
  v3 = 0;
  return printf("%ls\n", &v2);
}

//----- (0000000000402ACC) ----------------------------------------------------
int __fastcall printUnsignedLine(unsigned int a1)
{
  return printf("%u\n", a1);
}

//----- (0000000000402AED) ----------------------------------------------------
int __fastcall printHexUnsignedCharLine(unsigned __int8 a1)
{
  return printf("%02x\n", a1);
}

//----- (0000000000402B11) ----------------------------------------------------
int __fastcall printDoubleLine(double a1)
{
  return printf("%g\n", a1);
}

//----- (0000000000402B3C) ----------------------------------------------------
int __fastcall printStructLine(unsigned int *a1)
{
  return printf("%d -- %d\n", *a1, a1[1]);
}

//----- (0000000000402B68) ----------------------------------------------------
int __fastcall printBytesLine(__int64 a1, unsigned __int64 a2)
{
  unsigned __int64 i; // [rsp+18h] [rbp-8h]

  for ( i = 0LL; i < a2; ++i )
    printf("%02x", *(unsigned __int8 *)(a1 + i));
  return puts(s);
}

//----- (0000000000402BBF) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL;
        i < a2
     && (*__ctype_b_loc())[*(char *)(2 * i + v4)] & 0x1000
     && (*__ctype_b_loc())[*(char *)(2 * i + 1 + v4)] & 0x1000;
        ++i )
  {
    __isoc99_sscanf(2 * i + v4, "%02x", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 400930: using guessed type __int64 __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD);

//----- (0000000000402C98) ----------------------------------------------------
unsigned __int64 __fastcall decodeHexWChars(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  __int64 v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+24h] [rbp-Ch]
  unsigned __int64 i; // [rsp+28h] [rbp-8h]

  v4 = a3;
  for ( i = 0LL; i < a2 && iswxdigit(*(_DWORD *)(8 * i + v4)) && iswxdigit(*(_DWORD *)(8 * i + 4 + v4)); ++i )
  {
    __isoc99_swscanf(8 * i + v4, "%", &v5);
    *(_BYTE *)(i + a1) = v5;
  }
  return i;
}
// 4009F0: using guessed type __int64 __fastcall __isoc99_swscanf(_QWORD, _QWORD, _QWORD);

//----- (0000000000402D4C) ----------------------------------------------------
__int64 globalReturnsTrue()
{
  return 1LL;
}

//----- (0000000000402D57) ----------------------------------------------------
__int64 globalReturnsFalse()
{
  return 0LL;
}

//----- (0000000000402D62) ----------------------------------------------------
__int64 globalReturnsTrueOrFalse()
{
  return (unsigned int)(rand() % 2);
}

//----- (0000000000402D78) ----------------------------------------------------
void good1_17()
{
  ;
}

//----- (0000000000402D7E) ----------------------------------------------------
void good2_12()
{
  ;
}

//----- (0000000000402D84) ----------------------------------------------------
void good3()
{
  ;
}

//----- (0000000000402D8A) ----------------------------------------------------
void good4()
{
  ;
}

//----- (0000000000402D90) ----------------------------------------------------
void good5()
{
  ;
}

//----- (0000000000402D96) ----------------------------------------------------
void good6()
{
  ;
}

//----- (0000000000402D9C) ----------------------------------------------------
void good7()
{
  ;
}

//----- (0000000000402DA2) ----------------------------------------------------
void good8()
{
  ;
}

//----- (0000000000402DA8) ----------------------------------------------------
void good9()
{
  ;
}

//----- (0000000000402DAE) ----------------------------------------------------
void bad1()
{
  ;
}

//----- (0000000000402DB4) ----------------------------------------------------
void bad2()
{
  ;
}

//----- (0000000000402DBA) ----------------------------------------------------
void bad3()
{
  ;
}

//----- (0000000000402DC0) ----------------------------------------------------
void bad4()
{
  ;
}

//----- (0000000000402DC6) ----------------------------------------------------
void bad5()
{
  ;
}

//----- (0000000000402DCC) ----------------------------------------------------
void bad6()
{
  ;
}

//----- (0000000000402DD2) ----------------------------------------------------
void bad7()
{
  ;
}

//----- (0000000000402DD8) ----------------------------------------------------
void bad8()
{
  ;
}

//----- (0000000000402DDE) ----------------------------------------------------
void bad9()
{
  ;
}

//----- (0000000000402DE4) ----------------------------------------------------
void __fastcall __noreturn internal_start(void *a1)
{
  (*((void (__fastcall **)(_QWORD))a1 + 1))(*((_QWORD *)a1 + 2));
  pthread_exit(0LL);
}

//----- (0000000000402E17) ----------------------------------------------------
__int64 __fastcall stdThreadCreate(__int64 a1, __int64 a2, void **a3)
{
  __int64 result; // rax
  void **v4; // [rsp+8h] [rbp-28h]
  pthread_t newthread; // [rsp+20h] [rbp-10h]
  void *arg; // [rsp+28h] [rbp-8h]

  v4 = a3;
  *a3 = 0LL;
  arg = malloc(0x18uLL);
  if ( !arg )
    return 0LL;
  *((_QWORD *)arg + 1) = a1;
  *((_QWORD *)arg + 2) = a2;
  if ( pthread_create(&newthread, 0LL, (void *(*)(void *))internal_start, arg) )
  {
    free(arg);
    result = 0LL;
  }
  else
  {
    *(_QWORD *)arg = newthread;
    *v4 = arg;
    result = 1LL;
  }
  return result;
}

//----- (0000000000402EBB) ----------------------------------------------------
_BOOL8 __fastcall stdThreadJoin(pthread_t *a1)
{
  void *thread_return; // [rsp+18h] [rbp-8h]

  return pthread_join(*a1, &thread_return) == 0;
}

//----- (0000000000402EEF) ----------------------------------------------------
__int64 __fastcall stdThreadDestroy(void *a1)
{
  free(a1);
  return 1LL;
}

//----- (0000000000402F0E) ----------------------------------------------------
__int64 __fastcall stdThreadLockCreate(pthread_mutex_t **a1)
{
  __int64 result; // rax
  pthread_mutex_t *mutex; // [rsp+18h] [rbp-8h]

  *a1 = 0LL;
  mutex = (pthread_mutex_t *)malloc(0x28uLL);
  if ( !mutex )
    return 0LL;
  if ( pthread_mutex_init(mutex, 0LL) )
  {
    free(a1);
    result = 0LL;
  }
  else
  {
    *a1 = mutex;
    result = 1LL;
  }
  return result;
}

//----- (0000000000402F83) ----------------------------------------------------
int __fastcall stdThreadLockAcquire(pthread_mutex_t *a1)
{
  return pthread_mutex_lock(a1);
}

//----- (0000000000402F9D) ----------------------------------------------------
int __fastcall stdThreadLockRelease(pthread_mutex_t *a1)
{
  return pthread_mutex_unlock(a1);
}

//----- (0000000000402FB7) ----------------------------------------------------
void __fastcall stdThreadLockDestroy(pthread_mutex_t *a1)
{
  pthread_mutex_destroy(a1);
  free(a1);
}

//----- (0000000000402FE0) ----------------------------------------------------
void _libc_csu_init(void)
{
  __int64 v0; // rbx
  signed __int64 v1; // rbp

  v0 = 0LL;
  v1 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v1 )
  {
    do
      _frame_dummy_init_array_entry[v0++]();
    while ( v0 != v1 );
  }
}
// 605DD0: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 605DD8: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000403054) ----------------------------------------------------
void term_proc()
{
  ;
}

// ALL OK, 125 function(s) have been successfully decompiled
